// App.jsx — Dialed v6 (Liquid Glass)
import React, { useState, useEffect, useRef, useMemo, createContext, useContext } from "react";
import { EXERCISES, ACHIEVEMENTS, MUSCLE_COLORS, MUSCLE_GROUPS, getExerciseById, getPrimaryColor } from "./data";
import { getExerciseIcon } from "./icons";

// ─── THEME ──────────────────────────────────────────────────────────────────
const THEMES={emerald:{accent:"#34d399",name:"Emerald"},red:{accent:"#f87171",name:"Crimson"},blue:{accent:"#60a5fa",name:"Ice"},purple:{accent:"#a78bfa",name:"Violet"},orange:{accent:"#fb923c",name:"Blaze"},gold:{accent:"#fbbf24",name:"Gold"},pink:{accent:"#f472b6",name:"Rose"}};
const ThemeCtx=createContext(THEMES.emerald);const useTheme=()=>useContext(ThemeCtx);
const hx=(hex,a)=>{const r=parseInt(hex.slice(1,3),16),g=parseInt(hex.slice(3,5),16),b=parseInt(hex.slice(5,7),16);return`rgba(${r},${g},${b},${a})`;};
const dk=(hex,f=0.22)=>`rgb(${Math.round(parseInt(hex.slice(1,3),16)*f)},${Math.round(parseInt(hex.slice(3,5),16)*f)},${Math.round(parseInt(hex.slice(5,7),16)*f)})`;

// ─── STARTER ROUTINES ───────────────────────────────────────────────────────
const SR={2:[{name:"Full Body A",exercises:[{exerciseId:"squat",sets:3},{exerciseId:"bench_press",sets:3},{exerciseId:"seated_row",sets:3},{exerciseId:"cable_crunch",sets:3},{exerciseId:"tricep_pushdown",sets:3}]},{name:"Full Body B",exercises:[{exerciseId:"db_incline_bench",sets:3},{exerciseId:"lat_pulldown",sets:3},{exerciseId:"leg_extension",sets:3},{exerciseId:"db_curl",sets:3},{exerciseId:"leg_curl",sets:3},{exerciseId:"cable_lateral_raise",sets:3}]}],3:[{name:"Push",exercises:[{exerciseId:"bench_press",sets:3},{exerciseId:"db_shoulder_press",sets:3},{exerciseId:"db_incline_bench",sets:3},{exerciseId:"lateral_raise",sets:3},{exerciseId:"tricep_pushdown",sets:3}]},{name:"Pull",exercises:[{exerciseId:"barbell_row",sets:3},{exerciseId:"lat_pulldown",sets:3},{exerciseId:"seated_row",sets:3},{exerciseId:"face_pull",sets:3},{exerciseId:"barbell_curl",sets:3}]},{name:"Legs",exercises:[{exerciseId:"squat",sets:3},{exerciseId:"rdl",sets:3},{exerciseId:"leg_press",sets:3},{exerciseId:"leg_curl",sets:3},{exerciseId:"calf_raise",sets:3},{exerciseId:"hanging_leg_raise",sets:3}]}],4:[{name:"Upper A",exercises:[{exerciseId:"bench_press",sets:3},{exerciseId:"db_shoulder_press",sets:3},{exerciseId:"db_incline_bench",sets:3},{exerciseId:"lateral_raise",sets:3},{exerciseId:"tricep_pushdown",sets:3},{exerciseId:"cable_crunch",sets:3}]},{name:"Lower A",exercises:[{exerciseId:"squat",sets:3},{exerciseId:"leg_press",sets:3},{exerciseId:"leg_extension",sets:3},{exerciseId:"rdl",sets:3},{exerciseId:"calf_raise",sets:3}]},{name:"Upper B",exercises:[{exerciseId:"barbell_row",sets:3},{exerciseId:"lat_pulldown",sets:3},{exerciseId:"seated_row",sets:3},{exerciseId:"face_pull",sets:3},{exerciseId:"barbell_curl",sets:3},{exerciseId:"hammer_curl",sets:3}]},{name:"Lower B",exercises:[{exerciseId:"deadlift",sets:3},{exerciseId:"leg_curl",sets:3},{exerciseId:"hip_thrust",sets:3},{exerciseId:"bulgarian_split",sets:3},{exerciseId:"calf_raise",sets:3}]}]};SR[5]=SR[3];SR[6]=SR[3];
const ST={2:{mon:0,tue:null,wed:null,thu:1,fri:null,sat:null,sun:null},3:{mon:0,tue:null,wed:1,thu:null,fri:2,sat:null,sun:null},4:{mon:0,tue:1,wed:null,thu:2,fri:3,sat:null,sun:null},5:{mon:0,tue:1,wed:2,thu:0,fri:1,sat:null,sun:null},6:{mon:0,tue:1,wed:2,thu:0,fri:1,sat:2,sun:null}};

// ─── STORAGE ────────────────────────────────────────────────────────────────
const LS={get:(k,d=null)=>{try{const v=localStorage.getItem(k);return v?JSON.parse(v):d}catch{return d}},set:(k,v)=>localStorage.setItem(k,JSON.stringify(v))};
const uid=()=>Date.now().toString(36)+Math.random().toString(36).slice(2,7);

// ─── UTILS ──────────────────────────────────────────────────────────────────
const pad=n=>String(n).padStart(2,"0");
const fmtTime=s=>{const h=Math.floor(s/3600),m=Math.floor((s%3600)/60),sec=s%60;return h>0?`${pad(h)}:${pad(m)}:${pad(sec)}`:`${pad(m)}:${pad(sec)}`;};
const fmtDur=s=>{const h=Math.floor(s/3600),m=Math.floor((s%3600)/60);return h>0?`${h}h ${m}m`:`${m}m`;};
const est1RM=(w,r)=>r<=0||w<=0?0:Math.round(w*(36/(37-Math.min(r,36))));
const dKey=d=>`${d.getFullYear()}-${pad(d.getMonth()+1)}-${pad(d.getDate())}`;
const DS=["mon","tue","wed","thu","fri","sat","sun"];
const DL=["Mon","Tue","Wed","Thu","Fri","Sat","Sun"];
const fmt12=t=>{if(!t)return"";const[h,m]=t.split(":").map(Number);return`${h>12?h-12:h===0?12:h}:${pad(m)} ${h>=12?"PM":"AM"}`;};

function getStreakInfo(h,t=5){if(!h?.length)return{count:0,display:"0 this week"};const now=new Date(),s=new Date(now);s.setDate(now.getDate()-((now.getDay()+6)%7));s.setHours(0,0,0,0);const d=new Set();h.forEach(w=>{const x=new Date(w.date);if(x>=s)d.add(x.toDateString());});return{count:d.size,display:`${d.size}/${t} this week`};}
function getWeekVol(h,off=0){const now=new Date(),s=new Date(now);s.setDate(now.getDate()-((now.getDay()+6)%7)-off*7);s.setHours(0,0,0,0);const e=new Date(s);e.setDate(s.getDate()+7);const d=[0,0,0,0,0,0,0];let tot=0,wk=0,prs=0;(h||[]).forEach(w=>{const x=new Date(w.date);if(x>=s&&x<e){d[(x.getDay()+6)%7]+=w.totalVolume||0;tot+=w.totalVolume||0;wk++;prs+=(w.prs||[]).length;}});const el=new Date(e);el.setDate(el.getDate()-1);const fm=x=>x.toLocaleDateString("en-US",{month:"short",day:"numeric"});return{data:d,total:tot,workouts:wk,prs,label:`${fm(s)} – ${fm(el)}`,isCur:off===0};}
function getPrevBest(h,id){let b=null;(h||[]).forEach(w=>(w.exercises||[]).forEach(ex=>{if(ex.exerciseId===id)(ex.sets||[]).forEach(s=>{if(!b||(s.weight||0)>b.weight)b={weight:s.weight||0,reps:s.reps||0};});}));return b;}
function getPrevSets(h,id){for(let i=(h||[]).length-1;i>=0;i--){const ex=(h[i].exercises||[]).find(e=>e.exerciseId===id);if(ex?.sets?.length)return ex.sets;}return null;}
function getRecIds(h,n=6){const s=[];for(let i=(h||[]).length-1;i>=0;i--){(h[i].exercises||[]).forEach(ex=>{if(!s.includes(ex.exerciseId))s.push(ex.exerciseId);});if(s.length>=n)break;}return s.slice(0,n);}
function getExHist(h,id){const p=[];(h||[]).forEach(w=>{(w.exercises||[]).forEach(ex=>{if(ex.exerciseId===id){let bw=0,br=0,vol=0;(ex.sets||[]).forEach(s=>{const wt=s.weight||0,rp=s.reps||0;vol+=wt*rp;if(wt>bw||(wt===bw&&rp>br)){bw=wt;br=rp;}});if(bw>0||vol>0)p.push({date:w.date,bestWeight:bw,bestReps:br,volume:vol,est1rm:est1RM(bw,br)});}});});return p;}
function getMuscVol(h){const now=new Date(),s=new Date(now);s.setDate(now.getDate()-((now.getDay()+6)%7));s.setHours(0,0,0,0);const mv={};(h||[]).forEach(w=>{const d=new Date(w.date);if(d>=s)(w.exercises||[]).forEach(ex=>{const data=getExerciseById(ex.exerciseId);if(data)(data.primary||[]).forEach(m=>{if(!mv[m])mv[m]={sets:0,volume:0};(ex.sets||[]).forEach(st=>{mv[m].sets++;mv[m].volume+=(st.weight||0)*(st.reps||0);});});});});return mv;}
function getReport(h,t=5){const wk1=getWeekVol(h,1),wk2=getWeekVol(h,2);const now=new Date(),s=new Date(now);s.setDate(now.getDate()-((now.getDay()+6)%7)-7);s.setHours(0,0,0,0);const e=new Date(s);e.setDate(s.getDate()+7);const rm={};let ts=0,tp=0,lg=0,hv={w:0,ex:""};(h||[]).forEach(w=>{const d=new Date(w.date);if(d>=s&&d<e){rm[w.routineName]=(rm[w.routineName]||0)+1;if(w.duration>lg)lg=w.duration;tp+=(w.prs||[]).length;(w.exercises||[]).forEach(ex=>(ex.sets||[]).forEach(st=>{ts++;const wt=st.weight||0;if(wt>hv.w){hv.w=wt;const d2=getExerciseById(ex.exerciseId);hv.ex=d2?d2.name:"";};}));}});const vd=wk2.total>0?Math.round(((wk1.total-wk2.total)/wk2.total)*100):0;return{workouts:wk1.workouts,volume:wk1.total,volDiff:vd,sets:ts,prs:tp,routines:Object.entries(rm).map(([n,c])=>({name:n,count:c})),longest:lg,heaviest:hv,target:t,label:wk1.label,hasData:wk1.workouts>0};}
function getTodayPlan(routines){const tmpl=LS.get("dialed_weekly_template",{});const plans=LS.get("dialed_plans",{});const today=dKey(new Date());const dayKey=DS[(new Date().getDay()+6)%7];if(plans[today]){const p=plans[today];const r=routines.find(x=>x.id===p.routineId);return r?{routine:r,time:p.time}:null;}if(tmpl[dayKey]){const t=tmpl[dayKey];const r=routines.find(x=>x.id===t.routineId);return r?{routine:r,time:t.time}:null;}return null;}
function checkAch(h){const u=[],ct=(h||[]).length;let tv=0,tp=0,eu=new Set();if(ct>=1)u.push("first_workout");if(ct>=10)u.push("workouts_10");if(ct>=25)u.push("workouts_25");if(ct>=50)u.push("workouts_50");if(ct>=100)u.push("workouts_100");if(ct>=200)u.push("workouts_200");if(getStreakInfo(h).count>=5)u.push("streak_7");(h||[]).forEach(w=>{tv+=w.totalVolume||0;tp+=(w.prs||[]).length;(w.exercises||[]).forEach(ex=>{eu.add(ex.exerciseId);(ex.sets||[]).forEach(s=>{const wt=s.weight||0,id=ex.exerciseId;if(id==="bench_press"){if(wt>=135)u.push("bench_135");if(wt>=225)u.push("bench_225");if(wt>=315)u.push("bench_315");}if(id==="squat"){if(wt>=225)u.push("squat_225");if(wt>=315)u.push("squat_315");}if(id==="deadlift"){if(wt>=315)u.push("deadlift_315");if(wt>=405)u.push("deadlift_405");}});});});if(tv>=100000)u.push("vol_100k");if(tv>=500000)u.push("vol_500k");if(tv>=1000000)u.push("vol_1m");if(eu.size>=20)u.push("exercises_20");if(tp>=5)u.push("prs_5");if(tp>=25)u.push("prs_25");if(tp>=50)u.push("prs_50");const now2=new Date(),ws2=new Date(now2);ws2.setDate(now2.getDate()-((now2.getDay()+6)%7));ws2.setHours(0,0,0,0);const wm=new Set();(h||[]).forEach(w=>{if(new Date(w.date)>=ws2)(w.muscles||[]).forEach(m=>wm.add(m));});if(wm.size>=12)u.push("variety_all");return[...new Set(u)];}

// ─── GLOW BG ────────────────────────────────────────────────────────────────
function GlowBG({gold=false}){const{accent}=useTheme();const c=gold?"#fbbf24":accent;return<div style={{position:"fixed",inset:0,zIndex:0,pointerEvents:"none",overflow:"hidden"}}><div style={{position:"absolute",inset:0,background:"linear-gradient(165deg, #0a1a14 0%, #0d1510 30%, #0b1210 60%, #091110 100%)"}}/>
<div style={{position:"absolute",top:"-15%",left:"-10%",width:"65%",height:"55%",background:`radial-gradient(ellipse at 20% 25%, ${hx(c,gold?.14:.25)} 0%, transparent 55%)`}}/>
<div style={{position:"absolute",top:"30%",right:"-10%",width:"45%",height:"35%",background:`radial-gradient(ellipse at 80% 40%, ${hx(c,.1)} 0%, transparent 50%)`}}/>
<div style={{position:"absolute",top:"40%",left:"20%",width:"55%",height:"45%",background:`radial-gradient(ellipse at 40% 50%, ${hx(c,.05)} 0%, transparent 60%)`}}/>
<div style={{position:"absolute",bottom:"-8%",right:"-5%",width:"50%",height:"35%",background:`radial-gradient(ellipse at 70% 80%, ${hx(c,.08)} 0%, transparent 50%)`}}/>
<div style={{position:"absolute",bottom:"20%",left:"-10%",width:"40%",height:"30%",background:`radial-gradient(ellipse at 15% 70%, ${hx(c,.06)} 0%, transparent 50%)`}}/>
</div>;}

// ─── GLASS STYLES ───────────────────────────────────────────────────────────
const G={card:"backdrop-filter:blur(40px);-webkit-backdrop-filter:blur(40px);",shadow:"box-shadow:inset 0 1px 0 rgba(255,255,255,0.08),inset 0 -0.5px 0 rgba(0,0,0,0.1),0 4px 16px rgba(0,0,0,0.1);"};
const glass={background:"rgba(255,255,255,0.035)",border:"0.5px solid rgba(255,255,255,0.14)",borderRadius:22,padding:"16px",backdropFilter:"blur(40px)",WebkitBackdropFilter:"blur(40px)",boxShadow:"inset 0 1px 0 rgba(255,255,255,0.08), inset 0 -0.5px 0 rgba(0,0,0,0.1), 0 4px 16px rgba(0,0,0,0.1)"};
const glassSmall={...glass,borderRadius:14,padding:"13px 15px"};
const glassBg="rgba(255,255,255,0.035)";
const glassBdr="0.5px solid rgba(255,255,255,0.14)";
const glassSh="inset 0 1px 0 rgba(255,255,255,0.08), inset 0 -0.5px 0 rgba(0,0,0,0.1), 0 4px 16px rgba(0,0,0,0.1)";
const glassBlur={backdropFilter:"blur(40px)",WebkitBackdropFilter:"blur(40px)"};

function useS(){const{accent}=useTheme();return useMemo(()=>({
pg:{position:"relative",zIndex:1,minHeight:"100vh",padding:"0 20px 90px",fontFamily:"'Outfit',sans-serif"},
cd:{background:glassBg,border:glassBdr,borderRadius:22,padding:"16px",...glassBlur,boxShadow:glassSh},
cds:{background:glassBg,border:glassBdr,borderRadius:14,padding:"13px 15px",...glassBlur,boxShadow:glassSh},
cda(a){return{background:hx(a,.06),border:`0.5px solid ${hx(a,.2)}`,borderRadius:22,padding:"16px",...glassBlur,boxShadow:`inset 0 1px 0 ${hx(a,.08)}, inset 0 -0.5px 0 rgba(0,0,0,0.1), 0 4px 16px rgba(0,0,0,0.1)`};},
cdg:{background:"rgba(251,191,36,0.06)",border:"0.5px solid rgba(251,191,36,0.2)",borderRadius:22,padding:"16px",...glassBlur,boxShadow:"inset 0 1px 0 rgba(251,191,36,0.06), 0 4px 16px rgba(0,0,0,0.1)"},
tt:{fontSize:28,fontWeight:700,letterSpacing:-.8,color:"#fff",margin:0},
lb:{fontSize:11,fontWeight:600,letterSpacing:.5,color:"rgba(255,255,255,0.5)",margin:0},
mt:{color:"rgba(255,255,255,0.45)",fontSize:11.5,fontWeight:500},
bn:{fontSize:22,fontWeight:300,letterSpacing:-.8,color:"#fff"},
bp:{background:hx(accent,.08),color:accent,border:`0.5px solid ${hx(accent,.22)}`,borderRadius:14,padding:"14px 0",fontSize:15,fontWeight:600,width:"100%",cursor:"pointer",fontFamily:"'Outfit',sans-serif",...glassBlur,boxShadow:`inset 0 1px 0 ${hx(accent,.08)}`},
bg:{background:"rgba(255,255,255,0.04)",color:"rgba(255,255,255,0.55)",border:`0.5px solid rgba(255,255,255,0.12)`,borderRadius:14,padding:"13px 0",fontSize:13,fontWeight:500,width:"100%",cursor:"pointer",fontFamily:"'Outfit',sans-serif",...glassBlur,boxShadow:"inset 0 1px 0 rgba(255,255,255,0.06)"},
sv:{background:hx(accent,.12),color:accent,border:`0.5px solid ${hx(accent,.25)}`,borderRadius:100,padding:"8px 20px",fontSize:12,fontWeight:600,cursor:"pointer",fontFamily:"'Outfit',sans-serif"},
ip:{background:"rgba(255,255,255,0.05)",border:"0.5px solid rgba(255,255,255,0.12)",borderRadius:12,padding:"12px 14px",color:"#fff",fontSize:14,fontWeight:500,width:"100%",outline:"none",fontFamily:"'Outfit',sans-serif",boxSizing:"border-box"},
}),[accent]);}

const MP=({m})=>{const c=MUSCLE_COLORS[m]||"#94a3b8";return<span style={{display:"inline-block",padding:"2px 8px",borderRadius:6,fontSize:9,fontWeight:600,background:hx(c,.12),color:c,marginRight:4,marginBottom:3}}>{m}</span>;};
const EI=({id,size=36})=>{const ex=getExerciseById(id),c=getPrimaryColor(ex),I=getExerciseIcon(id);return<div style={{width:size,height:size,minWidth:size,borderRadius:Math.round(size*.28),background:hx(c,.1),border:`0.5px solid ${hx(c,.18)}`,display:"flex",alignItems:"center",justifyContent:"center",color:c,boxShadow:`inset 0 1px 0 ${hx(c,.08)}`}}><div style={{width:size*.55,height:size*.55}}><I/></div></div>;};

function Confirm({title,msg,ok,color,onOk,onNo}){const S=useS();return<div style={{position:"fixed",inset:0,zIndex:200,display:"flex",alignItems:"center",justifyContent:"center",fontFamily:"'Outfit',sans-serif"}}><div onClick={onNo} style={{position:"absolute",inset:0,background:"rgba(0,0,0,0.5)"}}/>
<div style={{position:"relative",width:"82%",maxWidth:340,...glass,padding:"24px 22px"}}><p style={{fontSize:17,fontWeight:700,color:"#fff",marginBottom:6}}>{title}</p><p style={{fontSize:13,fontWeight:500,color:"rgba(255,255,255,0.5)",marginBottom:20,lineHeight:1.5}}>{msg}</p><div style={{display:"flex",gap:8}}><button onClick={onNo} style={{...S.bg,flex:1}}>Go Back</button><button onClick={onOk} style={{...S.bp,flex:1,background:hx(color||"#f87171",.12),color:color||"#f87171",border:`0.5px solid ${hx(color||"#f87171",.25)}`}}>{ok}</button></div></div></div>;}

// ─── CHARTS ─────────────────────────────────────────────────────────────────
function Sparkline({data,color,w=80,h=28}){if(!data||data.length<2)return null;const mn=Math.min(...data),mx=Math.max(...data),rng=mx-mn||1;const pts=data.map((v,i)=>`${(i/(data.length-1))*w},${h-((v-mn)/rng)*(h-4)-2}`).join(" ");return<svg width={w} height={h} style={{display:"block"}}><polyline points={pts} fill="none" stroke={color} strokeWidth="1.5" strokeLinecap="round" strokeLinejoin="round"/></svg>;}
function LineChart({data,xKey,yKey,color,h=180}){if(!data||data.length<1)return<p style={{color:"rgba(255,255,255,0.3)",fontSize:12,textAlign:"center",padding:"20px 0"}}>Not enough data yet</p>;const vals=data.map(d=>d[yKey]),mn=Math.min(...vals),mx=Math.max(...vals),rng=mx-mn||1;const W=300,H=h,pL=40,cW=W-pL-8,cH=H-24-8;const pts=data.map((d,i)=>({x:pL+(data.length===1?.5:i/(data.length-1))*cW,y:8+(1-(d[yKey]-mn)/rng)*cH}));const yLb=[mn,mn+rng/2,mx].map(v=>Math.round(v));return<svg viewBox={`0 0 ${W} ${H}`} style={{width:"100%",height:"auto",display:"block"}}>{[0,.5,1].map((f,i)=><line key={i} x1={pL} y1={8+(1-f)*cH} x2={W-8} y2={8+(1-f)*cH} stroke="rgba(255,255,255,0.06)" strokeWidth="0.5"/>)}{yLb.map((v,i)=><text key={i} x={pL-6} y={8+(1-[0,.5,1][i])*cH+3} textAnchor="end" fill="rgba(255,255,255,0.3)" fontSize="8" fontFamily="Outfit">{v.toLocaleString()}</text>)}{pts.length>1&&<><polyline points={pts.map(p=>`${p.x},${p.y}`).join(" ")} fill="none" stroke={color} strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"/><polygon points={`${pts[0].x},${8+cH} ${pts.map(p=>`${p.x},${p.y}`).join(" ")} ${pts[pts.length-1].x},${8+cH}`} fill="url(#ag)" opacity="0.3"/></>}<defs><linearGradient id="ag" x1="0" y1="0" x2="0" y2="1"><stop offset="0%" stopColor={color} stopOpacity="0.3"/><stop offset="100%" stopColor={color} stopOpacity="0"/></linearGradient></defs>{pts.map((p,i)=><circle key={i} cx={p.x} cy={p.y} r="3" fill={color} stroke="rgba(10,17,14,0.8)" strokeWidth="1.5"/>)}{data.length>1&&<><text x={pts[0].x} y={H-4} textAnchor="start" fill="rgba(255,255,255,0.25)" fontSize="7" fontFamily="Outfit">{new Date(data[0][xKey]).toLocaleDateString("en-US",{month:"short",day:"numeric"})}</text><text x={pts[pts.length-1].x} y={H-4} textAnchor="end" fill="rgba(255,255,255,0.25)" fontSize="7" fontFamily="Outfit">{new Date(data[data.length-1][xKey]).toLocaleDateString("en-US",{month:"short",day:"numeric"})}</text></>}</svg>;}

// ─── NAV ────────────────────────────────────────────────────────────────────
function Nav({tab,setTab}){const{accent}=useTheme();const items=[{id:"home",label:"Home",d:"M3 9.5L12 3l9 6.5V20a1 1 0 01-1 1H4a1 1 0 01-1-1V9.5z|M9 21V13h6v8"},{id:"history",label:"History",d:"M12 8v4l3 3|circle:12,12,9"},{id:"calendar",label:"Calendar",d:"rect:3,4,18,18,2|M16 2v4|M8 2v4|M3 10h18"},{id:"awards",label:"Awards",d:"circle:12,8,6|M15.477 12.89L17 22l-5-3-5 3 1.523-9.11"}];return<nav style={{position:"fixed",bottom:0,left:0,right:0,zIndex:50,background:"rgba(10,18,14,0.7)",...glassBlur,backdropFilter:"blur(30px)",WebkitBackdropFilter:"blur(30px)",borderTop:"0.5px solid rgba(255,255,255,0.08)",display:"flex",justifyContent:"space-around",height:62,alignItems:"center",boxShadow:"inset 0 1px 0 rgba(255,255,255,0.05)"}}>{items.map(it=>{const a=tab===it.id;return<button key={it.id} onClick={()=>setTab(it.id)} style={{background:"none",border:"none",display:"flex",flexDirection:"column",alignItems:"center",cursor:"pointer",padding:"4px 14px",gap:3}}><svg width="20" height="20" viewBox="0 0 24 24" fill="none" stroke={a?"#fff":"rgba(255,255,255,0.35)"} strokeWidth="1.6" strokeLinecap="round" strokeLinejoin="round">{it.d.split("|").map((p,i)=>{if(p.startsWith("circle:")){const[cx,cy,r]=p.slice(7).split(",");return<circle key={i} cx={cx} cy={cy} r={r}/>;}if(p.startsWith("rect:")){const[x,y,w,h,rx]=p.slice(5).split(",");return<rect key={i} x={x} y={y} width={w} height={h} rx={rx}/>;}return<path key={i} d={p}/>;})}</svg><span style={{fontSize:9,fontWeight:a?600:500,color:a?"#fff":"rgba(255,255,255,0.35)"}}>{it.label}</span></button>;})}</nav>;}

// ─── SETTINGS ───────────────────────────────────────────────────────────────
function Settings({profile,onClose,onUpdate}){const{accent}=useTheme();const S=useS();const tid=profile.theme||"emerald";return<div style={{position:"fixed",inset:0,zIndex:100,display:"flex",flexDirection:"column",justifyContent:"flex-end",fontFamily:"'Outfit',sans-serif"}}><div onClick={onClose} style={{position:"absolute",inset:0,background:"rgba(0,0,0,0.5)"}}/><div style={{position:"relative",...glass,borderRadius:"22px 22px 0 0",maxHeight:"75vh",overflow:"auto"}}><div style={{display:"flex",justifyContent:"center",padding:"10px 0 6px"}}><div style={{width:36,height:4,borderRadius:2,background:"rgba(255,255,255,0.2)"}}/></div><div style={{padding:"6px 22px 28px"}}>
<p style={{fontSize:18,fontWeight:700,color:"#fff",marginBottom:20}}>Settings</p>
<p style={{...S.lb,marginBottom:8}}>NAME</p><input value={profile.name||""} onChange={e=>onUpdate({...profile,name:e.target.value})} style={{...S.ip,marginBottom:20}}/>
<p style={{...S.lb,marginBottom:10}}>ACCENT COLOR</p><div style={{display:"grid",gridTemplateColumns:"repeat(7,1fr)",gap:8,marginBottom:28}}>{Object.entries(THEMES).map(([id,t])=><button key={id} onClick={()=>onUpdate({...profile,theme:id})} style={{width:"100%",aspectRatio:"1",borderRadius:12,border:tid===id?`2px solid ${t.accent}`:"2px solid transparent",background:hx(t.accent,.18),cursor:"pointer",display:"flex",alignItems:"center",justifyContent:"center",position:"relative"}}><div style={{width:16,height:16,borderRadius:"50%",background:t.accent}}/>{tid===id&&<div style={{position:"absolute",bottom:-16,left:"50%",transform:"translateX(-50%)",fontSize:8,fontWeight:600,color:t.accent,whiteSpace:"nowrap"}}>{t.name}</div>}</button>)}</div>
<p style={{...S.lb,marginBottom:8}}>WEEKLY GOAL</p><div style={{display:"flex",gap:6,marginBottom:20}}>{[2,3,4,5,6].map(n=><button key={n} onClick={()=>onUpdate({...profile,weeklyGoal:n})} style={{flex:1,padding:"10px 0",borderRadius:10,fontSize:14,fontWeight:600,cursor:"pointer",fontFamily:"'Outfit',sans-serif",background:(profile.weeklyGoal||5)===n?hx(accent,.12):"rgba(255,255,255,0.04)",color:(profile.weeklyGoal||5)===n?accent:"rgba(255,255,255,0.45)",border:(profile.weeklyGoal||5)===n?`0.5px solid ${hx(accent,.25)}`:"0.5px solid rgba(255,255,255,0.08)"}}>{n}x</button>)}</div>
<p style={{...S.lb,marginBottom:8}}>WEIGHT UNIT</p><div style={{display:"flex",gap:6,marginBottom:24}}>{["lbs","kg"].map(u=><button key={u} onClick={()=>onUpdate({...profile,unit:u})} style={{flex:1,padding:"10px 0",borderRadius:10,fontSize:14,fontWeight:600,cursor:"pointer",fontFamily:"'Outfit',sans-serif",background:(profile.unit||"lbs")===u?hx(accent,.12):"rgba(255,255,255,0.04)",color:(profile.unit||"lbs")===u?accent:"rgba(255,255,255,0.45)",border:(profile.unit||"lbs")===u?`0.5px solid ${hx(accent,.25)}`:"0.5px solid rgba(255,255,255,0.08)"}}>{u}</button>)}</div>
<button onClick={onClose} style={S.bp}>Done</button>
</div></div></div>;}

// ─── TIME PICKER ────────────────────────────────────────────────────────────
function TimePicker({value,onChange}){const{accent}=useTheme();const S=useS();const parsed=useMemo(()=>{if(!value)return{hr:12,min:0,ampm:"AM"};const[h,m]=value.split(":").map(Number);return{hr:h>12?h-12:h===0?12:h,min:m,ampm:h>=12?"PM":"AM"};},[value]);const[hr,setHr]=useState(parsed.hr);const[min,setMin]=useState(parsed.min);const[ampm,setAmpm]=useState(parsed.ampm);const[open,setOpen]=useState(false);useEffect(()=>{if(value){const p=value.split(":").map(Number);setHr(p[0]>12?p[0]-12:p[0]===0?12:p[0]);setMin(p[1]);setAmpm(p[0]>=12?"PM":"AM");}},[value]);const commit=()=>{let h24=hr;if(ampm==="PM"&&hr!==12)h24=hr+12;if(ampm==="AM"&&hr===12)h24=0;onChange(`${pad(h24)}:${pad(min)}`);setOpen(false);};
return<div style={{position:"relative"}}><button onClick={()=>setOpen(!open)} style={{...S.ip,padding:"8px 10px",fontSize:12,cursor:"pointer",textAlign:"center",color:value?"#fff":"rgba(255,255,255,0.4)",width:100}}>{value?fmt12(value):"Set time"}</button>
{open&&<div style={{position:"absolute",top:"100%",right:0,zIndex:50,marginTop:4,...glass,padding:14,width:220}}>
<div style={{display:"flex",gap:4,marginBottom:12,background:"rgba(255,255,255,0.04)",borderRadius:8,padding:3}}>{["AM","PM"].map(p=><button key={p} onClick={()=>setAmpm(p)} style={{flex:1,padding:"8px 0",borderRadius:6,fontSize:12,fontWeight:700,cursor:"pointer",fontFamily:"'Outfit',sans-serif",background:ampm===p?hx(accent,.12):"transparent",color:ampm===p?accent:"rgba(255,255,255,0.45)",border:ampm===p?`0.5px solid ${hx(accent,.2)}`:"none"}}>{p}</button>)}</div>
<p style={{fontSize:9,fontWeight:600,letterSpacing:.8,color:"rgba(255,255,255,0.4)",marginBottom:6}}>HOUR</p>
<div style={{display:"grid",gridTemplateColumns:"repeat(4,1fr)",gap:4,marginBottom:12}}>{[12,1,2,3,4,5,6,7,8,9,10,11].map(h=><button key={h} onClick={()=>setHr(h)} style={{padding:"7px 0",borderRadius:8,fontSize:13,fontWeight:hr===h?600:400,cursor:"pointer",fontFamily:"'Outfit',sans-serif",background:hr===h?hx(accent,.12):"rgba(255,255,255,0.03)",color:hr===h?accent:"rgba(255,255,255,0.55)",border:hr===h?`0.5px solid ${hx(accent,.2)}`:"0.5px solid transparent"}}>{h}</button>)}</div>
<p style={{fontSize:9,fontWeight:600,letterSpacing:.8,color:"rgba(255,255,255,0.4)",marginBottom:6}}>MINUTE</p>
<div style={{display:"grid",gridTemplateColumns:"repeat(4,1fr)",gap:4,marginBottom:12}}>{[0,15,30,45].map(m=><button key={m} onClick={()=>setMin(m)} style={{padding:"7px 0",borderRadius:8,fontSize:13,fontWeight:min===m?600:400,cursor:"pointer",fontFamily:"'Outfit',sans-serif",background:min===m?hx(accent,.12):"rgba(255,255,255,0.03)",color:min===m?accent:"rgba(255,255,255,0.55)",border:min===m?`0.5px solid ${hx(accent,.2)}`:"0.5px solid transparent"}}>:{pad(m)}</button>)}</div>
<div style={{display:"flex",gap:6}}><button onClick={()=>{onChange(null);setOpen(false);}} style={{flex:1,padding:"8px 0",borderRadius:8,fontSize:11,fontWeight:600,cursor:"pointer",fontFamily:"'Outfit',sans-serif",background:"rgba(255,255,255,0.04)",color:"rgba(255,255,255,0.4)",border:"none"}}>Clear</button><button onClick={commit} style={{flex:1,padding:"8px 0",borderRadius:8,fontSize:11,fontWeight:600,cursor:"pointer",fontFamily:"'Outfit',sans-serif",background:hx(accent,.12),color:accent,border:`0.5px solid ${hx(accent,.2)}`}}>Set</button></div>
</div>}</div>;}

// ─── TEMPLATE EDITOR ────────────────────────────────────────────────────────
function TemplateEditor({routines,onClose}){const{accent}=useTheme();const S=useS();const[tmpl,setTmpl]=useState(()=>{const t=LS.get("dialed_weekly_template",{});const r={};DS.forEach(d=>r[d]=t[d]||null);return r;});const save=()=>{LS.set("dialed_weekly_template",tmpl);onClose();};const setDay=(day,rid)=>setTmpl({...tmpl,[day]:rid?{routineId:rid,time:tmpl[day]?.time||null}:null});const setTime=(day,t)=>{if(tmpl[day])setTmpl({...tmpl,[day]:{...tmpl[day],time:t||null}});};
return<div style={{position:"fixed",inset:0,zIndex:100,display:"flex",flexDirection:"column",justifyContent:"flex-end",fontFamily:"'Outfit',sans-serif"}}><div onClick={onClose} style={{position:"absolute",inset:0,background:"rgba(0,0,0,0.5)"}}/><div style={{position:"relative",...glass,borderRadius:"22px 22px 0 0",maxHeight:"85vh",overflow:"auto"}}><div style={{display:"flex",justifyContent:"center",padding:"10px 0 6px"}}><div style={{width:36,height:4,borderRadius:2,background:"rgba(255,255,255,0.2)"}}/></div><div style={{padding:"6px 22px 28px"}}>
<div style={{display:"flex",justifyContent:"space-between",alignItems:"center",marginBottom:20}}><p style={{fontSize:18,fontWeight:700,color:"#fff"}}>Weekly Schedule</p><button onClick={save} style={S.sv}>Save</button></div>
{DS.map((d,i)=>{const e=tmpl[d];return<div key={d} style={{display:"flex",alignItems:"center",gap:12,padding:"14px 0",borderBottom:"1px solid rgba(255,255,255,0.06)"}}><span style={{fontSize:13,fontWeight:700,color:"rgba(255,255,255,0.7)",width:36}}>{DL[i]}</span><div style={{flex:1}}><select value={e?.routineId||""} onChange={ev=>setDay(d,ev.target.value||null)} style={{...S.ip,padding:"8px 12px",fontSize:12,appearance:"none",cursor:"pointer",color:e?"#fff":"rgba(255,255,255,0.4)"}}><option value="" style={{background:"#0e1814"}}>Rest Day</option>{routines.map(r=><option key={r.id} value={r.id} style={{background:"#0e1814"}}>{r.name}</option>)}</select></div>{e&&<TimePicker value={e.time} onChange={t=>setTime(d,t)}/>}</div>;})}
<button onClick={()=>{const c={};DS.forEach(d=>c[d]=null);setTmpl(c);}} style={{...S.bg,marginTop:16,color:"#f87171",borderColor:"rgba(248,113,113,0.15)"}}>Clear Schedule</button>
</div></div></div>;}

// ─── ONBOARDING ─────────────────────────────────────────────────────────────
function Onboarding({onComplete}){const{accent}=useTheme();const S=useS();const[step,setStep]=useState(0),[name,setName]=useState(""),[goal,setGoal]=useState(""),[freq,setFreq]=useState(0);const goals=["Build Muscle","Lose Fat","Get Stronger","Stay Active"];
const finish=()=>{const f=freq||3;const starters=(SR[f]||SR[3]).map(r=>({...r,id:uid(),createdAt:Date.now()}));LS.set("dialed_routines",starters);const ts=ST[f]||ST[3];const tmpl={};DS.forEach(d=>{const idx=ts[d];tmpl[d]=idx!=null?{routineId:starters[idx%starters.length].id,time:null}:null;});LS.set("dialed_weekly_template",tmpl);LS.set("dialed_profile",{name:name||"Athlete",goal,onboarded:true,theme:"emerald",weeklyGoal:f,unit:"lbs"});onComplete();};
const next=()=>{if(step<3)setStep(step+1);else finish();};
return<div style={{...S.pg,display:"flex",flexDirection:"column",justifyContent:"center",minHeight:"100vh",padding:"40px 24px"}}><GlowBG/><div style={{position:"relative",zIndex:1}}>
{step===0&&<><div style={{fontSize:44,fontWeight:800,color:"#fff",letterSpacing:-1.5,lineHeight:1.1,marginBottom:12}}>Get<br/><span style={{color:accent}}>Dialed</span> In.</div><p style={{...S.mt,fontSize:15,marginBottom:48,lineHeight:1.6}}>Track every rep. Hit every PR.<br/>No fluff, just progress.</p></>}
{step===1&&<><p style={{...S.lb,marginBottom:10}}>WHAT'S YOUR NAME?</p><div style={{fontSize:28,fontWeight:700,color:"#fff",letterSpacing:-.8,marginBottom:24}}>Let's get to know you.</div><input value={name} onChange={e=>setName(e.target.value)} placeholder="Your name" style={{...S.ip,fontSize:18,padding:"16px 18px"}} autoFocus/></>}
{step===2&&<><p style={{...S.lb,marginBottom:10}}>YOUR GOAL</p><div style={{fontSize:28,fontWeight:700,color:"#fff",letterSpacing:-.8,marginBottom:24}}>What are you training for?</div><div style={{display:"flex",flexDirection:"column",gap:8}}>{goals.map(g=><button key={g} onClick={()=>setGoal(g)} style={{...(goal===g?S.cda(accent):S.cd),textAlign:"left",cursor:"pointer",fontSize:15,fontWeight:600,color:goal===g?accent:"#fff"}}>{g}</button>)}</div></>}
{step===3&&<><p style={{...S.lb,marginBottom:10}}>TRAINING FREQUENCY</p><div style={{fontSize:28,fontWeight:700,color:"#fff",letterSpacing:-.8,marginBottom:8}}>How many days a week?</div><p style={{...S.mt,marginBottom:24}}>We'll build your starter plan around this.</p><div style={{display:"flex",flexDirection:"column",gap:8}}>{[{n:2,l:"2x / week",s:"Full Body A & B"},{n:3,l:"3x / week",s:"Push / Pull / Legs"},{n:4,l:"4x / week",s:"Upper / Lower split"},{n:5,l:"5x / week",s:"Push / Pull / Legs × 2"},{n:6,l:"6x / week",s:"Push / Pull / Legs × 2"}].map(o=><button key={o.n} onClick={()=>setFreq(o.n)} style={{...(freq===o.n?S.cda(accent):S.cd),textAlign:"left",cursor:"pointer"}}><div style={{fontSize:15,fontWeight:600,color:freq===o.n?accent:"#fff"}}>{o.l}</div><div style={{fontSize:11,fontWeight:500,color:freq===o.n?hx(accent,.6):"rgba(255,255,255,0.4)",marginTop:2}}>{o.s}</div></button>)}</div></>}
<div style={{marginTop:40,display:"flex",flexDirection:"column",gap:10}}><button onClick={next} style={S.bp}>{step===0?"Let's Go":step===3?"Build My Plan":"Continue"}</button><button onClick={finish} style={{background:"none",border:"none",color:"rgba(255,255,255,0.3)",fontSize:12,fontWeight:500,cursor:"pointer",padding:8,fontFamily:"'Outfit',sans-serif"}}>Skip</button></div>
<div style={{display:"flex",gap:6,justifyContent:"center",marginTop:20}}>{[0,1,2,3].map(i=><div key={i} style={{width:i===step?20:6,height:6,borderRadius:3,background:i===step?accent:"rgba(255,255,255,0.12)",transition:"all 0.3s"}}/>)}</div>
</div></div>;}

// ─── EXERCISE DETAIL ────────────────────────────────────────────────────────
function ExDetail({exerciseId,history,onClose}){const{accent}=useTheme();const S=useS();const data=getExerciseById(exerciseId);const[mode,setMode]=useState("weight");const[range,setRange]=useState("all");const allPts=useMemo(()=>getExHist(history,exerciseId),[history,exerciseId]);const filtered=useMemo(()=>{if(range==="all")return allPts;const ms={["1m"]:30,["3m"]:90,["6m"]:180,["1y"]:365}[range]||9999;return allPts.filter(p=>new Date(p.date)>=new Date(Date.now()-ms*86400000));},[allPts,range]);const yKey=mode==="weight"?"bestWeight":mode==="volume"?"volume":"est1rm";const atb=allPts.length>0?{weight:Math.max(...allPts.map(p=>p.bestWeight)),reps:Math.max(...allPts.map(p=>p.bestReps)),e1rm:Math.max(...allPts.map(p=>p.est1rm)),vol:Math.max(...allPts.map(p=>p.volume))}:null;if(!data)return null;
return<div style={{position:"fixed",inset:0,zIndex:100,fontFamily:"'Outfit',sans-serif",background:"transparent",overflow:"auto"}}><GlowBG/><div style={{position:"relative",zIndex:1,padding:"52px 20px 40px"}}>
<div style={{display:"flex",alignItems:"center",gap:12,marginBottom:24}}><button onClick={onClose} style={{width:38,height:38,borderRadius:12,...glassSmall,padding:0,display:"flex",alignItems:"center",justifyContent:"center",cursor:"pointer",color:"#fff",border:glassBdr}}><svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round"><path d="M19 12H5M12 5l-7 7 7 7"/></svg></button><EI id={exerciseId} size={42}/><div><div style={{fontSize:18,fontWeight:700,color:"#fff"}}>{data.name}</div><div style={{display:"flex",marginTop:3}}>{data.primary.map(m=><MP key={m} m={m}/>)}</div></div></div>
<div style={{display:"flex",gap:4,marginBottom:12,...glassSmall,padding:3}}>{[["weight","Weight"],["volume","Volume"],["e1rm","Est 1RM"]].map(([k,l])=><button key={k} onClick={()=>setMode(k)} style={{flex:1,padding:"8px 0",borderRadius:10,fontSize:12,fontWeight:600,cursor:"pointer",fontFamily:"'Outfit',sans-serif",background:mode===k?hx(accent,.12):"transparent",color:mode===k?accent:"rgba(255,255,255,0.45)",border:mode===k?`0.5px solid ${hx(accent,.2)}`:"none"}}>{l}</button>)}</div>
<div style={{display:"flex",gap:4,marginBottom:20}}>{["1m","3m","6m","1y","all"].map(r=><button key={r} onClick={()=>setRange(r)} style={{flex:1,padding:"6px 0",borderRadius:8,fontSize:10,fontWeight:600,cursor:"pointer",fontFamily:"'Outfit',sans-serif",background:range===r?hx(accent,.12):"transparent",color:range===r?accent:"rgba(255,255,255,0.35)",border:range===r?`0.5px solid ${hx(accent,.2)}`:"none"}}>{r.toUpperCase()}</button>)}</div>
<div style={{...S.cd,marginBottom:16,padding:"16px 12px"}}><LineChart data={filtered} xKey="date" yKey={yKey} color={accent} h={200}/></div>
{atb&&<div style={S.cda(accent)}><p style={{...S.lb,color:accent,marginBottom:12}}>PERSONAL RECORDS</p><div style={{display:"grid",gridTemplateColumns:"1fr 1fr",gap:12}}>{[["Best Weight",`${atb.weight} lbs`],["Est 1RM",`${atb.e1rm} lbs`],["Best Reps",atb.reps],["Best Volume",atb.vol.toLocaleString()]].map(([l,v])=><div key={l}><div style={{fontSize:9,fontWeight:600,color:"rgba(255,255,255,0.35)",marginBottom:3}}>{l}</div><div style={{fontSize:20,fontWeight:300,color:"#fff"}}>{v}</div></div>)}</div></div>}
<p style={{...S.lb,margin:"16px 0 8px"}}>RECENT SESSIONS</p>{allPts.slice(-5).reverse().map((p,i)=><div key={i} style={{...S.cds,marginBottom:6,display:"flex",justifyContent:"space-between",alignItems:"center"}}><span style={{fontSize:11,fontWeight:500,color:"rgba(255,255,255,0.5)"}}>{new Date(p.date).toLocaleDateString("en-US",{month:"short",day:"numeric"})}</span><span style={{fontSize:13,fontWeight:600,color:"#fff"}}>{p.bestWeight}×{p.bestReps}</span><span style={{fontSize:10,fontWeight:500,color:"rgba(255,255,255,0.35)"}}>{p.volume.toLocaleString()} vol</span></div>)}
</div></div>;}

// ─── BODY WEIGHT ────────────────────────────────────────────────────────────
function BWDetail({profile,onClose}){const{accent}=useTheme();const S=useS();const[range,setRange]=useState("3m");const bwData=LS.get("dialed_bodyweight",[]).sort((a,b)=>a.date.localeCompare(b.date));const unit=profile.unit||"lbs";const filtered=useMemo(()=>{if(range==="all")return bwData;const ms={["1m"]:30,["3m"]:90,["6m"]:180,["1y"]:365}[range]||9999;return bwData.filter(p=>new Date(p.date)>=new Date(Date.now()-ms*86400000));},[bwData,range]);const stats=bwData.length>0?{cur:bwData[bwData.length-1].weight,start:bwData[0].weight,low:Math.min(...bwData.map(e=>e.weight)),high:Math.max(...bwData.map(e=>e.weight)),change:Math.round((bwData[bwData.length-1].weight-bwData[0].weight)*10)/10}:null;
return<div style={{position:"fixed",inset:0,zIndex:100,fontFamily:"'Outfit',sans-serif",overflow:"auto"}}><GlowBG/><div style={{position:"relative",zIndex:1,padding:"52px 20px 40px"}}>
<div style={{display:"flex",alignItems:"center",gap:12,marginBottom:24}}><button onClick={onClose} style={{width:38,height:38,borderRadius:12,...glassSmall,padding:0,display:"flex",alignItems:"center",justifyContent:"center",cursor:"pointer",color:"#fff",border:glassBdr}}><svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round"><path d="M19 12H5M12 5l-7 7 7 7"/></svg></button><div style={{fontSize:18,fontWeight:700,color:"#fff"}}>Body Weight</div></div>
<div style={{display:"flex",gap:4,marginBottom:20}}>{["1m","3m","6m","1y","all"].map(r=><button key={r} onClick={()=>setRange(r)} style={{flex:1,padding:"6px 0",borderRadius:8,fontSize:10,fontWeight:600,cursor:"pointer",fontFamily:"'Outfit',sans-serif",background:range===r?hx(accent,.12):"transparent",color:range===r?accent:"rgba(255,255,255,0.35)",border:range===r?`0.5px solid ${hx(accent,.2)}`:"none"}}>{r.toUpperCase()}</button>)}</div>
<div style={{...S.cd,marginBottom:16,padding:"16px 12px"}}><LineChart data={filtered.map(e=>({date:e.date,weight:e.weight}))} xKey="date" yKey="weight" color={accent} h={200}/></div>
{stats&&<div style={S.cda(accent)}><div style={{display:"grid",gridTemplateColumns:"1fr 1fr",gap:12}}>{[["Current",`${stats.cur} ${unit}`],["Starting",`${stats.start} ${unit}`],["Change",`${stats.change>0?"+":""}${stats.change} ${unit}`],["Range",`${stats.low}–${stats.high}`]].map(([l,v])=><div key={l}><div style={{fontSize:9,fontWeight:600,color:"rgba(255,255,255,0.35)",marginBottom:3}}>{l}</div><div style={{fontSize:20,fontWeight:300,color:l==="Change"?(stats.change>0?"#f87171":"#34d399"):"#fff"}}>{v}</div></div>)}</div></div>}
</div></div>;}

function BWModal({profile,onClose,onLog}){const S=useS();const[val,setVal]=useState("");const unit=profile.unit||"lbs";const today=dKey(new Date());const bw=LS.get("dialed_bodyweight",[]);const te=bw.find(e=>e.date===today);useEffect(()=>{if(te)setVal(String(te.weight));},[]);const save=()=>{const n=parseFloat(val);if(!n)return;const u=bw.filter(e=>e.date!==today);u.push({date:today,weight:n});LS.set("dialed_bodyweight",u);onLog();onClose();};return<div style={{position:"fixed",inset:0,zIndex:100,display:"flex",alignItems:"center",justifyContent:"center",fontFamily:"'Outfit',sans-serif"}}><div onClick={onClose} style={{position:"absolute",inset:0,background:"rgba(0,0,0,0.5)"}}/><div style={{position:"relative",width:"85%",maxWidth:340,...glass,padding:24}}><p style={{fontSize:17,fontWeight:700,color:"#fff",marginBottom:12}}>Log Body Weight</p><div style={{display:"flex",gap:8,alignItems:"center",marginBottom:16}}><input type="number" inputMode="decimal" value={val} onChange={e=>setVal(e.target.value)} placeholder="0" style={{...S.ip,fontSize:24,fontWeight:300,textAlign:"center",padding:"14px"}} autoFocus/><span style={{fontSize:14,fontWeight:600,color:"rgba(255,255,255,0.45)"}}>{unit}</span></div><button onClick={save} style={S.bp}>{te?"Update":"Log"}</button></div></div>;}

// ─── HOME ───────────────────────────────────────────────────────────────────
function HomeScreen({profile,history,routines,onStartRoutine,onNewRoutine,onEditRoutine,onQuickStart,onOpenSettings}){
const{accent}=useTheme();const S=useS();const[weekOff,setWeekOff]=useState(0),[showBW,setShowBW]=useState(false),[showBWD,setShowBWD]=useState(false),[bwK,setBwK]=useState(0),[mvMode,setMvMode]=useState("sets");
const wk=getWeekVol(history,weekOff),streak=getStreakInfo(history,profile.weeklyGoal||5);
const mv=getMuscVol(history),mvE=Object.entries(mv).sort((a,b)=>b[1][mvMode==="sets"?"sets":"volume"]-a[1][mvMode==="sets"?"sets":"volume"]);const mvMax=mvE.length>0?Math.max(...mvE.map(([,v])=>v[mvMode==="sets"?"sets":"volume"])):1;
const bwData=LS.get("dialed_bodyweight",[]);const todayBW=bwData.find(e=>e.date===dKey(new Date()));
const dys=["M","T","W","T","F","S","S"],tIdx=(new Date().getDay()+6)%7,maxV=Math.max(...wk.data,1),unit=profile.unit||"lbs";
const plan=getTodayPlan(routines);const now=new Date();

return<div style={S.pg}>
<div style={{display:"flex",justifyContent:"space-between",alignItems:"center",paddingTop:56,marginBottom:28}}>
<div><div style={{fontSize:14,fontWeight:500,color:"rgba(255,255,255,0.45)",marginBottom:2}}>{now.toLocaleDateString("en-US",{weekday:"long",month:"short",day:"numeric"})}</div><div style={S.tt}>Hey, {profile.name||"Athlete"}</div></div>
<div style={{display:"flex",alignItems:"center",gap:10}}>
{streak.count>0&&<div style={{...glassSmall,padding:"5px 12px",fontSize:11,fontWeight:600,color:"rgba(255,255,255,0.7)",borderRadius:100}}>{streak.display}</div>}
<button onClick={onOpenSettings} style={{width:38,height:38,borderRadius:12,background:glassBg,border:glassBdr,...glassBlur,boxShadow:glassSh,padding:0,display:"flex",alignItems:"center",justifyContent:"center",cursor:"pointer"}}><svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="rgba(255,255,255,0.55)" strokeWidth="1.8"><circle cx="12" cy="12" r="3"/><path d="M19.4 15a1.65 1.65 0 00.33 1.82l.06.06a2 2 0 010 2.83 2 2 0 01-2.83 0l-.06-.06a1.65 1.65 0 00-1.82-.33 1.65 1.65 0 00-1 1.51V21a2 2 0 01-4 0v-.09A1.65 1.65 0 009 19.4a1.65 1.65 0 00-1.82.33l-.06.06a2 2 0 01-2.83-2.83l.06-.06A1.65 1.65 0 004.68 15a1.65 1.65 0 00-1.51-1H3a2 2 0 010-4h.09A1.65 1.65 0 004.6 9a1.65 1.65 0 00-.33-1.82l-.06-.06a2 2 0 012.83-2.83l.06.06A1.65 1.65 0 009 4.68a1.65 1.65 0 001-1.51V3a2 2 0 014 0v.09a1.65 1.65 0 001 1.51 1.65 1.65 0 001.82-.33l.06-.06a2 2 0 012.83 2.83l-.06.06A1.65 1.65 0 0019.4 9a1.65 1.65 0 001.51 1H21a2 2 0 010 4h-.09a1.65 1.65 0 00-1.51 1z"/></svg></button>
</div></div>

{plan&&<div style={{...S.cd,marginBottom:10}}><div style={{display:"flex",justifyContent:"space-between",alignItems:"center",marginBottom:14}}><div style={S.lb}>TODAY'S PLAN</div>{plan.time&&<div style={{fontSize:11,fontWeight:500,color:"rgba(255,255,255,0.45)"}}>{fmt12(plan.time)}</div>}</div>
<div style={{display:"flex",alignItems:"center",gap:14,marginBottom:16}}><EI id={plan.routine.exercises[0]?.exerciseId||"bench_press"} size={48}/><div style={{flex:1}}><div style={{fontSize:18,fontWeight:600,color:"#fff"}}>{plan.routine.name}</div><div style={{fontSize:11,fontWeight:500,color:"rgba(255,255,255,0.45)",marginTop:4}}>{plan.routine.exercises.length} exercises</div></div></div>
<button onClick={()=>onStartRoutine(plan.routine)} style={S.bp}>Begin Workout</button></div>}

<button onClick={onQuickStart} style={{...S.bg,marginBottom:12}}>Quick Start</button>

<div style={{display:"flex",gap:8,marginBottom:12}}>
<div style={{flex:1,...S.cd,padding:"16px 14px"}}><div style={{display:"flex",justifyContent:"space-between",marginBottom:10}}><div style={S.lb}>This week</div>{streak.count>0&&<div style={{background:hx(accent,.08),border:`0.5px solid ${hx(accent,.18)}`,borderRadius:6,padding:"2px 7px",fontSize:9,fontWeight:600,color:accent}}>{streak.count}/{profile.weeklyGoal||5}</div>}</div>
<div style={{display:"flex",alignItems:"flex-end",gap:4,height:44,marginBottom:8}}>{dys.map((d,i)=>{const h=wk.data[i]>0?Math.max(14,(wk.data[i]/maxV)*100):8;const isT=i===tIdx&&wk.isCur;const isF=i>tIdx&&wk.isCur;return<div key={i} style={{flex:1,height:`${h}%`,minHeight:4,borderRadius:3,background:isF?"rgba(255,255,255,0.04)":isT?`linear-gradient(180deg, ${accent} 0%, ${hx(accent,.4)} 100%)`:wk.data[i]>0?`linear-gradient(180deg, ${hx(accent,.5)} 0%, ${hx(accent,.12)} 100%)`:"rgba(255,255,255,0.04)",boxShadow:isT&&wk.data[i]>0?`0 0 10px ${hx(accent,.25)}`:"none"}}/>;})}</div>
<div style={S.bn}>{wk.total>=1000?`${(wk.total/1000).toFixed(1)}k`:wk.total.toLocaleString()}</div><div style={{fontSize:10,fontWeight:500,color:"rgba(255,255,255,0.4)"}}>lbs volume</div></div>
<div style={{display:"flex",flexDirection:"column",gap:8,width:115}}>
<div style={{flex:1,...S.cd,padding:14,display:"flex",flexDirection:"column",justifyContent:"center"}}><div style={{fontSize:22,fontWeight:300,color:accent}}>{wk.prs}</div><div style={{fontSize:10,fontWeight:500,color:"rgba(255,255,255,0.45)",marginTop:2}}>PRs hit</div></div>
<button onClick={()=>todayBW?setShowBWD(true):setShowBW(true)} style={{flex:1,...S.cd,padding:14,display:"flex",flexDirection:"column",justifyContent:"center",cursor:"pointer",textAlign:"left",border:glassBdr}}>{todayBW?<><div style={{fontSize:20,fontWeight:300,color:"#fff"}}>{todayBW.weight}<span style={{fontSize:10,color:"rgba(255,255,255,0.4)"}}> {unit}</span></div><div style={{fontSize:10,fontWeight:500,color:"rgba(255,255,255,0.45)",marginTop:2}}>body wt</div></>:<div style={{fontSize:12,fontWeight:500,color:"rgba(255,255,255,0.35)"}}>Log weight</div>}</button>
</div></div>

{mvE.length>0&&<div style={{...S.cd,marginBottom:12,padding:"14px 16px"}}><div style={{display:"flex",justifyContent:"space-between",marginBottom:10}}><div style={S.lb}>MUSCLES THIS WEEK</div></div>{mvE.slice(0,5).map(([m,v])=>{const val=v[mvMode==="sets"?"sets":"volume"];const pct=Math.max(8,(val/mvMax)*100);const c=MUSCLE_COLORS[m]||"#94a3b8";return<div key={m} style={{display:"flex",alignItems:"center",gap:8,marginBottom:5}}><span style={{fontSize:10,fontWeight:500,color:"rgba(255,255,255,0.55)",width:55,textAlign:"right"}}>{m}</span><div style={{flex:1,height:7,background:"rgba(255,255,255,0.04)",borderRadius:4,overflow:"hidden"}}><div style={{height:"100%",width:`${pct}%`,borderRadius:4,background:`linear-gradient(90deg, ${hx(c,.55)}, ${hx(c,.18)})`}}/></div><span style={{fontSize:10,fontWeight:500,color:"rgba(255,255,255,0.4)",width:20,textAlign:"right"}}>{val}</span></div>;})}</div>}

<div style={{display:"flex",justifyContent:"space-between",alignItems:"center",marginBottom:12}}><div style={S.lb}>ROUTINES</div><button onClick={onNewRoutine} style={{fontSize:13,fontWeight:600,color:accent,background:"none",border:"none",cursor:"pointer",fontFamily:"'Outfit',sans-serif"}}>+ New</button></div>
<div style={{display:"flex",flexDirection:"column",gap:6}}>{routines.map(r=>{const muscles=[...new Set(r.exercises.flatMap(e=>{const ex=getExerciseById(e.exerciseId);return ex?ex.primary:[];}))];const pc=muscles.length>0?MUSCLE_COLORS[muscles[0]]||"#94a3b8":"#94a3b8";
return<div key={r.id} onClick={()=>onEditRoutine(r)} style={{...S.cds,display:"flex",justifyContent:"space-between",alignItems:"center",cursor:"pointer"}}>
<div style={{display:"flex",alignItems:"center",gap:12}}><div style={{width:36,height:36,borderRadius:10,background:hx(pc,.08),border:`0.5px solid ${hx(pc,.18)}`,display:"flex",alignItems:"center",justifyContent:"center"}}>{r.exercises[0]&&<div style={{width:16,height:16,color:pc}}>{React.createElement(getExerciseIcon(r.exercises[0].exerciseId))}</div>}</div>
<div><div style={{fontSize:14,fontWeight:600,color:"#fff"}}>{r.name}</div><div style={{fontSize:11,fontWeight:400,color:"rgba(255,255,255,0.45)",marginTop:1}}>{muscles.join(", ")}</div></div></div>
<svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="rgba(255,255,255,0.3)" strokeWidth="2" strokeLinecap="round"><path d="M9 18l6-6-6-6"/></svg></div>;})}
{routines.length===0&&<div style={{...S.cd,textAlign:"center",padding:28}}><p style={S.mt}>No routines yet</p></div>}</div>
{showBW&&<BWModal profile={profile} onClose={()=>setShowBW(false)} onLog={()=>setBwK(k=>k+1)}/>}
{showBWD&&<BWDetail profile={profile} onClose={()=>setShowBWD(false)}/>}
</div>;}

// ─── ROUTINE BUILDER ────────────────────────────────────────────────────────
function RoutineBuilder({routine,onSave,onBack,onDelete,history}){const{accent}=useTheme();const S=useS();const[name,setName]=useState(routine?routine.name:"New Routine");const[exercises,setExercises]=useState(routine?routine.exercises.map(e=>({...e})):[]);const[showPicker,setShowPicker]=useState(false);
const addEx=ex=>{setExercises([...exercises,{exerciseId:ex.id,sets:3}]);setShowPicker(false);};const rmEx=i=>setExercises(exercises.filter((_,j)=>j!==i));const setSets=(i,d)=>{const u=[...exercises];u[i]={...u[i],sets:Math.max(1,Math.min(10,u[i].sets+d))};setExercises(u);};const save=()=>onSave({id:routine?routine.id:uid(),name,exercises,createdAt:routine?routine.createdAt:Date.now()});
return<><div style={S.pg}><div style={{display:"flex",justifyContent:"space-between",alignItems:"center",paddingTop:56,marginBottom:8}}><button onClick={onBack} style={{width:38,height:38,borderRadius:12,background:glassBg,border:glassBdr,...glassBlur,boxShadow:glassSh,padding:0,display:"flex",alignItems:"center",justifyContent:"center",cursor:"pointer",color:"#fff"}}><svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round"><path d="M19 12H5M12 5l-7 7 7 7"/></svg></button><div style={{display:"flex",gap:8}}>{routine&&<button onClick={()=>{onDelete(routine.id);onBack();}} style={{...S.sv,background:"rgba(248,113,113,0.1)",color:"#f87171",border:"0.5px solid rgba(248,113,113,0.2)"}}>Delete</button>}<button onClick={save} style={S.sv}>Save</button></div></div>
<input value={name} onChange={e=>setName(e.target.value)} style={{background:"none",border:"none",outline:"none",fontSize:22,fontWeight:700,color:"#fff",letterSpacing:-.5,width:"100%",fontFamily:"'Outfit',sans-serif",padding:"8px 0"}}/>
<div style={{height:1,background:"rgba(255,255,255,0.08)",marginBottom:24}}/>
<div style={{display:"flex",justifyContent:"space-between",alignItems:"center",marginBottom:14}}><div style={S.lb}>EXERCISES · {exercises.length}</div><button onClick={()=>setShowPicker(true)} style={{fontSize:13,fontWeight:600,color:accent,background:"none",border:"none",cursor:"pointer",fontFamily:"'Outfit',sans-serif"}}>+ Add</button></div>
<div style={{display:"flex",flexDirection:"column",gap:8}}>{exercises.map((ex,i)=>{const data=getExerciseById(ex.exerciseId);if(!data)return null;return<div key={i} style={S.cds}>
<div style={{display:"flex",alignItems:"center",gap:12,marginBottom:10}}><EI id={ex.exerciseId} size={38}/><div style={{flex:1}}><div style={{fontSize:13,fontWeight:600,color:"#fff"}}>{data.name}</div><div style={{display:"flex",flexWrap:"wrap",marginTop:2}}>{data.primary.map(m=><MP key={m} m={m}/>)}</div></div><button onClick={()=>rmEx(i)} style={{background:"none",border:"none",color:"rgba(255,255,255,0.25)",cursor:"pointer",fontSize:14}}>×</button></div>
<div style={{height:1,background:"rgba(255,255,255,0.06)",marginBottom:10}}/>
<div style={{display:"flex",alignItems:"center",gap:12}}><span style={{fontSize:10,fontWeight:600,color:"rgba(255,255,255,0.35)"}}>SETS</span><button onClick={()=>setSets(i,-1)} style={{width:28,height:28,borderRadius:8,background:glassBg,border:glassBdr,color:"#fff",cursor:"pointer",fontSize:14,display:"flex",alignItems:"center",justifyContent:"center"}}>−</button><span style={{fontSize:16,fontWeight:700,color:"#fff",minWidth:20,textAlign:"center"}}>{ex.sets}</span><button onClick={()=>setSets(i,1)} style={{width:28,height:28,borderRadius:8,background:glassBg,border:glassBdr,color:"#fff",cursor:"pointer",fontSize:14,display:"flex",alignItems:"center",justifyContent:"center"}}>+</button></div></div>;})}</div>
<button onClick={()=>setShowPicker(true)} style={{width:"100%",padding:16,borderRadius:14,border:"1.5px dashed rgba(255,255,255,0.12)",background:"none",color:"rgba(255,255,255,0.35)",fontSize:13,fontWeight:600,cursor:"pointer",marginTop:12,fontFamily:"'Outfit',sans-serif"}}>+ Add Exercise</button></div>
{showPicker&&<ExPicker onSelect={addEx} onClose={()=>setShowPicker(false)} existingIds={exercises.map(e=>e.exerciseId)} history={history}/>}</>;
}

// ─── EXERCISE PICKER ────────────────────────────────────────────────────────
function ExPicker({onSelect,onClose,existingIds=[],history}){const{accent}=useTheme();const S=useS();const[search,setSearch]=useState(""),[filter,setFilter]=useState("All"),[showC,setShowC]=useState(false),[cN,setCN]=useState(""),[cT,setCT]=useState("weighted"),[cM,setCM]=useState([]);
const allEx=useMemo(()=>[...EXERCISES,...LS.get("dialed_custom_exercises",[])],[]);const recIds=useMemo(()=>getRecIds(history),[history]);
const filtered=useMemo(()=>{let l=filter==="All"?allEx:allEx.filter(e=>e.primary.includes(filter)||(e.secondary&&e.secondary.includes(filter)));if(search)l=l.filter(e=>e.name.toLowerCase().includes(search.toLowerCase()));return l.filter(e=>!existingIds.includes(e.id));},[search,filter,allEx,existingIds]);
const recEx=useMemo(()=>{if(search||filter!=="All")return[];return recIds.map(id=>allEx.find(e=>e.id===id)).filter(e=>e&&!existingIds.includes(e.id));},[recIds,allEx,existingIds,search,filter]);
const createC=()=>{if(!cN.trim())return;const ex={id:"custom_"+uid(),name:cN.trim(),primary:cM.length?cM:["Full Body"],secondary:[],type:cT};const existing=LS.get("dialed_custom_exercises",[]);LS.set("dialed_custom_exercises",[...existing,ex]);onSelect(ex);setShowC(false);setCN("");setCM([]);};
const Row=({ex})=><button onClick={()=>onSelect(ex)} style={{display:"flex",alignItems:"center",gap:12,width:"100%",padding:"12px 0",background:"none",border:"none",borderBottom:"1px solid rgba(255,255,255,0.05)",cursor:"pointer",textAlign:"left"}}><EI id={ex.id} size={36}/><div style={{flex:1}}><div style={{fontSize:13,fontWeight:600,color:"#fff"}}>{ex.name}</div><div style={{display:"flex",flexWrap:"wrap",marginTop:2}}>{ex.primary.map(m=><MP key={m} m={m}/>)}</div></div></button>;
return<div style={{position:"fixed",inset:0,zIndex:100,display:"flex",flexDirection:"column",justifyContent:"flex-end",fontFamily:"'Outfit',sans-serif"}}><div onClick={onClose} style={{position:"absolute",inset:0,background:"rgba(0,0,0,0.5)"}}/><div style={{position:"relative",background:glassBg,border:glassBdr,...glassBlur,boxShadow:glassSh,borderRadius:"22px 22px 0 0",maxHeight:"85vh",display:"flex",flexDirection:"column"}}><div style={{display:"flex",justifyContent:"center",padding:"10px 0 6px"}}><div style={{width:36,height:4,borderRadius:2,background:"rgba(255,255,255,0.2)"}}/></div>
<div style={{padding:"0 20px"}}><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search exercises..." style={{...S.ip,marginBottom:12}} autoFocus/>
<div style={{display:"flex",gap:6,overflowX:"auto",paddingBottom:12}}>{["All",...MUSCLE_GROUPS].map(m=><button key={m} onClick={()=>setFilter(m)} style={{flexShrink:0,padding:"6px 14px",borderRadius:100,fontSize:11,fontWeight:600,cursor:"pointer",fontFamily:"'Outfit',sans-serif",background:filter===m?hx(accent,.12):"rgba(255,255,255,0.04)",color:filter===m?accent:"rgba(255,255,255,0.45)",border:filter===m?`0.5px solid ${hx(accent,.2)}`:"none"}}>{m}</button>)}</div></div>
<div style={{flex:1,overflowY:"auto",padding:"0 20px 20px"}}>
{!showC&&<button onClick={()=>setShowC(true)} style={{width:"100%",padding:14,borderRadius:12,border:`1.5px dashed ${hx(accent,.3)}`,background:"none",color:accent,fontSize:12,fontWeight:600,cursor:"pointer",marginBottom:8,fontFamily:"'Outfit',sans-serif"}}>+ Create Custom Exercise</button>}
{showC&&<div style={S.cda(accent)}><input value={cN} onChange={e=>setCN(e.target.value)} placeholder="Exercise name" style={{...S.ip,marginBottom:10}}/>
<div style={{display:"flex",gap:6,marginBottom:10}}>{["weighted","bodyweight","timed"].map(t=><button key={t} onClick={()=>setCT(t)} style={{flex:1,padding:"8px 0",borderRadius:8,fontSize:11,fontWeight:600,cursor:"pointer",fontFamily:"'Outfit',sans-serif",background:cT===t?hx(accent,.12):"rgba(255,255,255,0.04)",color:cT===t?accent:"rgba(255,255,255,0.4)",border:cT===t?`0.5px solid ${hx(accent,.2)}`:"none",textTransform:"capitalize"}}>{t}</button>)}</div>
<div style={{display:"flex",flexWrap:"wrap",gap:4,marginBottom:10}}>{MUSCLE_GROUPS.map(m=><button key={m} onClick={()=>setCM(p=>p.includes(m)?p.filter(x=>x!==m):[...p,m])} style={{padding:"4px 10px",borderRadius:6,fontSize:9,fontWeight:700,cursor:"pointer",fontFamily:"'Outfit',sans-serif",background:cM.includes(m)?hx(MUSCLE_COLORS[m],.18):"rgba(255,255,255,0.04)",color:cM.includes(m)?MUSCLE_COLORS[m]:"rgba(255,255,255,0.3)",border:"none"}}>{m}</button>)}</div>
<div style={{display:"flex",gap:8}}><button onClick={()=>setShowC(false)} style={{...S.bg,flex:1}}>Cancel</button><button onClick={createC} style={{...S.bp,flex:1}}>Create</button></div></div>}
{recEx.length>0&&<><p style={{...S.lb,color:hx(accent,.6),marginBottom:6,marginTop:4}}>RECENT</p>{recEx.map(ex=><Row key={ex.id} ex={ex}/>)}<div style={{height:1,background:"rgba(255,255,255,0.06)",margin:"8px 0"}}/></>}
{filtered.map(ex=><Row key={ex.id} ex={ex}/>)}{filtered.length===0&&<p style={{...S.mt,textAlign:"center",padding:20}}>No exercises found</p>}
</div></div></div>;}

// ─── LIVE WORKOUT ───────────────────────────────────────────────────────────
function LiveWorkout({routine,history,onFinish,onCancel}){const{accent}=useTheme();const S=useS();const[elapsed,setElapsed]=useState(0);const[exercises,setExercises]=useState(()=>(routine?routine.exercises:[]).map(ex=>{const prev=getPrevSets(history,ex.exerciseId);return{exerciseId:ex.exerciseId,sets:Array.from({length:ex.sets},(_,i)=>({reps:"",weight:"",done:false,isPR:false,prevReps:prev?.[i]?.reps||"",prevWeight:prev?.[i]?.weight||""}))};}));const[note,setNote]=useState("");const[showNote,setShowNote]=useState(false);const[prFlash,setPrFlash]=useState(null);const[showPk,setShowPk]=useState(false);const[showCan,setShowCan]=useState(false);
useEffect(()=>{const t=setInterval(()=>setElapsed(e=>e+1),1000);return()=>clearInterval(t);},[]);
const tS=exercises.reduce((a,e)=>a+e.sets.length,0),dS=exercises.reduce((a,e)=>a+e.sets.filter(s=>s.done).length,0),prog=tS>0?(dS/tS)*100:0;
const upSet=(ei,si,f,v)=>setExercises(exercises.map((ex,i)=>i!==ei?ex:{...ex,sets:ex.sets.map((s,j)=>j===si?{...s,[f]:v}:s)}));
const togDone=(ei,si)=>{const u=[...exercises];const set={...u[ei].sets[si]};set.done=!set.done;if(set.done){const best=getPrevBest(history,u[ei].exerciseId);const w=parseFloat(set.weight)||0,r=parseInt(set.reps)||0;if(best&&w>0&&(w>best.weight||(w===best.weight&&r>best.reps))){set.isPR=true;const d=getExerciseById(u[ei].exerciseId);setPrFlash(d?d.name:"PR");setTimeout(()=>setPrFlash(null),2200);}}else set.isPR=false;u[ei]={...u[ei],sets:u[ei].sets.map((s,j)=>j===si?set:s)};setExercises(u);};
const addSet=ei=>{const u=[...exercises];const prev=getPrevSets(history,u[ei].exerciseId);const si=u[ei].sets.length;u[ei]={...u[ei],sets:[...u[ei].sets,{reps:"",weight:"",done:false,isPR:false,prevReps:prev?.[si]?.reps||"",prevWeight:prev?.[si]?.weight||""}]};setExercises(u);};
const rmSet=(ei,si)=>{const u=[...exercises];if(u[ei].sets.length<=1)return;u[ei]={...u[ei],sets:u[ei].sets.filter((_,j)=>j!==si)};setExercises(u);};
const rmEx=ei=>setExercises(exercises.filter((_,i)=>i!==ei));
const addEx=ex=>{const prev=getPrevSets(history,ex.id);setExercises([...exercises,{exerciseId:ex.id,sets:Array.from({length:3},(_,i)=>({reps:"",weight:"",done:false,isPR:false,prevReps:prev?.[i]?.reps||"",prevWeight:prev?.[i]?.weight||""}))}]);setShowPk(false);};
const finish=()=>{const prs=[],muscles=new Set();let tv=0;const exData=exercises.map(ex=>{const d=getExerciseById(ex.exerciseId);if(d)d.primary.forEach(m=>muscles.add(m));const sets=ex.sets.filter(s=>s.done).map(s=>{const w=parseFloat(s.weight)||0,r=parseInt(s.reps)||0;tv+=w*r;if(s.isPR)prs.push({exerciseId:ex.exerciseId,weight:w,reps:r});return{weight:w,reps:r,isPR:s.isPR};});return{exerciseId:ex.exerciseId,sets};}).filter(e=>e.sets.length>0);onFinish({id:uid(),routineName:routine?routine.name:"Quick Workout",exercises:exData,duration:elapsed,totalVolume:tv,prs,muscles:[...muscles],date:new Date().toISOString(),note:note||null,setsCompleted:dS});};
const aI=exercises.findIndex(ex=>ex.sets.some(s=>!s.done));

return<><div style={{position:"relative",zIndex:1,minHeight:"100vh",paddingBottom:40,fontFamily:"'Outfit',sans-serif"}}>
<div style={{position:"sticky",top:0,zIndex:20,background:"rgba(10,18,14,0.85)",...glassBlur,backdropFilter:"blur(24px)"}}>
<div style={{display:"flex",justifyContent:"space-between",alignItems:"center",padding:"52px 20px 10px"}}><div><div style={{fontSize:11,fontWeight:500,color:"rgba(255,255,255,0.4)"}}>{routine?routine.name:"Quick Workout"}</div><div style={{fontSize:30,fontWeight:300,color:accent,fontVariantNumeric:"tabular-nums"}}>{fmtTime(elapsed)}</div></div><div style={{display:"flex",gap:8,alignItems:"center"}}><span style={{fontSize:11,fontWeight:600,color:"rgba(255,255,255,0.45)",background:glassBg,border:glassBdr,borderRadius:100,padding:"4px 10px"}}>{dS}/{tS}</span><button onClick={finish} style={S.sv}>Finish</button></div></div>
<div style={{height:3,background:"rgba(255,255,255,0.06)"}}><div style={{height:"100%",width:`${prog}%`,background:hx(accent,.7),borderRadius:2,transition:"width 0.4s"}}/></div></div>

<div style={{padding:"16px 20px"}}>{exercises.map((ex,ei)=>{const data=getExerciseById(ex.exerciseId);if(!data)return null;const allDone=ex.sets.every(s=>s.done);
return<div key={ei} style={{...S.cds,marginBottom:10,border:allDone?`0.5px solid ${hx(accent,.3)}`:glassBdr,opacity:ei>aI&&aI>=0?.7:1}}>
<div style={{display:"flex",alignItems:"center",gap:12,marginBottom:12}}><EI id={ex.exerciseId} size={34}/><div style={{flex:1}}><div style={{fontSize:13,fontWeight:600,color:"#fff"}}>{data.name}</div><div style={{display:"flex",flexWrap:"wrap",marginTop:2}}>{data.primary.map(m=><MP key={m} m={m}/>)}</div></div><button onClick={()=>rmEx(ei)} style={{background:"none",border:"none",color:"rgba(255,255,255,0.25)",cursor:"pointer",fontSize:14}}>×</button></div>
<div style={{display:"grid",gridTemplateColumns:"28px 1fr 1fr 36px",gap:8,marginBottom:6}}><span style={{...S.lb,fontSize:8}}>SET</span><span style={{...S.lb,fontSize:8}}>WEIGHT</span><span style={{...S.lb,fontSize:8}}>REPS</span><span/></div>
{ex.sets.map((set,si)=>{const iBg=set.done?hx(accent,.05):"rgba(255,255,255,0.05)";const iBdr=set.done?`0.5px solid ${hx(accent,.22)}`:"0.5px solid rgba(255,255,255,0.12)";
return<div key={si} style={{display:"grid",gridTemplateColumns:"28px 1fr 1fr 36px",gap:8,marginBottom:6,alignItems:"center"}}>
<span style={{fontSize:12,fontWeight:700,color:set.done?accent:"rgba(255,255,255,0.45)",textAlign:"center"}}>{si+1}</span>
<input type="number" inputMode="decimal" value={set.weight} onChange={e=>upSet(ei,si,"weight",e.target.value)} placeholder={set.prevWeight?String(set.prevWeight):"0"} style={{...S.ip,padding:"9px 10px",fontSize:13,fontWeight:600,textAlign:"center",background:iBg,border:iBdr}}/>
<input type="number" inputMode="numeric" value={set.reps} onChange={e=>upSet(ei,si,"reps",e.target.value)} placeholder={set.prevReps?String(set.prevReps):"0"} style={{...S.ip,padding:"9px 10px",fontSize:13,fontWeight:600,textAlign:"center",background:iBg,border:iBdr}}/>
<button onClick={()=>togDone(ei,si)} style={{width:36,height:36,borderRadius:10,border:"none",cursor:"pointer",background:set.isPR?"rgba(251,191,36,0.12)":set.done?hx(accent,.1):"rgba(255,255,255,0.05)",color:set.isPR?"#fbbf24":set.done?accent:"rgba(255,255,255,0.35)",fontSize:14,display:"flex",alignItems:"center",justifyContent:"center"}}>{set.isPR?"★":set.done?"✓":"○"}</button></div>;})}
<button onClick={()=>addSet(ei)} style={{width:"100%",padding:8,borderRadius:8,border:"1px dashed rgba(255,255,255,0.1)",background:"none",color:"rgba(255,255,255,0.3)",fontSize:11,fontWeight:600,cursor:"pointer",marginTop:4,fontFamily:"'Outfit',sans-serif"}}>+ Add Set</button></div>;})}
<button onClick={()=>setShowPk(true)} style={{...S.bg,marginTop:8}}>+ Add Exercise</button>
<button onClick={()=>setShowCan(true)} style={{...S.bg,marginTop:8,color:"#f87171",borderColor:"rgba(248,113,113,0.15)"}}>Cancel Workout</button>
</div></div>
{showNote&&<div style={{position:"fixed",inset:0,zIndex:100,display:"flex",alignItems:"center",justifyContent:"center",fontFamily:"'Outfit',sans-serif"}}><div onClick={()=>setShowNote(false)} style={{position:"absolute",inset:0,background:"rgba(0,0,0,0.5)"}}/><div style={{position:"relative",width:"85%",maxWidth:360,...glass,padding:24}}><p style={{fontSize:17,fontWeight:700,color:"#fff",marginBottom:12}}>Workout Note</p><textarea value={note} onChange={e=>setNote(e.target.value)} placeholder="How was the session?" style={{...S.ip,minHeight:100,resize:"vertical"}}/><button onClick={()=>setShowNote(false)} style={{...S.bp,marginTop:12}}>Done</button></div></div>}
{showCan&&<Confirm title="Cancel workout?" msg="All progress will be lost." ok="Cancel Workout" color="#f87171" onOk={onCancel} onNo={()=>setShowCan(false)}/>}
{prFlash&&<div style={{position:"fixed",inset:0,zIndex:200,display:"flex",flexDirection:"column",alignItems:"center",justifyContent:"center",background:"rgba(0,0,0,0.7)",fontFamily:"'Outfit',sans-serif"}}><div style={{fontSize:56,marginBottom:12}}>⭐</div><div style={{fontSize:10,fontWeight:800,letterSpacing:3,color:"#fbbf24",marginBottom:6}}>PERSONAL RECORD</div><div style={{fontSize:18,fontWeight:700,color:"#fff"}}>{prFlash}</div></div>}
{showPk&&<ExPicker onSelect={addEx} onClose={()=>setShowPk(false)} existingIds={exercises.map(e=>e.exerciseId)} history={history}/>}
</>;}

// ─── SUMMARY ────────────────────────────────────────────────────────────────
function WorkoutSummary({workout,onDone}){const{accent}=useTheme();const S=useS();
return<div style={S.pg}><GlowBG gold/><div style={{position:"relative",zIndex:1,paddingTop:80,textAlign:"center"}}><div style={{width:56,height:56,borderRadius:16,...glass,display:"flex",alignItems:"center",justifyContent:"center",margin:"0 auto 16px",fontSize:26,background:"rgba(251,191,36,0.08)",border:"0.5px solid rgba(251,191,36,0.2)"}}>🏁</div><h1 style={{...S.tt,fontSize:26,marginBottom:4}}>Workout Done</h1><p style={{...S.mt,marginBottom:24}}>{workout.routineName}</p>
<div style={{display:"grid",gridTemplateColumns:"1fr 1fr 1fr",gap:8,marginBottom:16}}>{[["TIME",fmtDur(workout.duration)],["LBS",(workout.totalVolume||0).toLocaleString()],["SETS",workout.setsCompleted]].map(([l,v])=><div key={l} style={{...S.cd,padding:"14px 12px",textAlign:"center"}}><div style={{...S.lb,marginBottom:4}}>{l}</div><div style={{fontSize:18,fontWeight:300,color:"#fff"}}>{v}</div></div>)}</div>
{workout.prs?.length>0&&<div style={{...S.cdg,textAlign:"left",marginBottom:12}}><p style={{fontSize:9,fontWeight:700,letterSpacing:1.5,color:"#fbbf24",marginBottom:10}}>⭐ PERSONAL RECORDS</p>{workout.prs.map((pr,i)=>{const d=getExerciseById(pr.exerciseId);return<div key={i} style={{display:"flex",justifyContent:"space-between",padding:"6px 0",borderTop:i>0?"1px solid rgba(251,191,36,0.08)":"none"}}><span style={{fontSize:13,fontWeight:600,color:"#fff"}}>{d?d.name:pr.exerciseId}</span><span style={{fontSize:13,fontWeight:700,color:"#fbbf24"}}>{pr.weight}×{pr.reps}</span></div>;})}</div>}
{workout.muscles?.length>0&&<div style={{...S.cd,textAlign:"left",marginBottom:12}}><div style={{...S.lb,marginBottom:8}}>MUSCLES TRAINED</div><div style={{display:"flex",flexWrap:"wrap"}}>{workout.muscles.map(m=><MP key={m} m={m}/>)}</div></div>}
<div style={{display:"flex",gap:8,marginTop:12}}><button onClick={onDone} style={{...S.bp,flex:1}}>Done</button></div>
</div></div>;}

// ─── HISTORY ────────────────────────────────────────────────────────────────
function HistoryScreen({history,onDeleteWorkout,onOpenExDetail}){const{accent}=useTheme();const S=useS();const[exp,setExp]=useState(null);const[cDel,setCDel]=useState(null);return<div style={S.pg}><div style={{paddingTop:56,marginBottom:24}}><h1 style={S.tt}>History</h1><p style={{...S.mt,marginTop:4}}>{history.length} workouts logged</p></div>{history.length===0?<div style={{...S.cd,textAlign:"center",padding:28}}><p style={S.mt}>No workouts yet</p></div>:<div style={{display:"flex",flexDirection:"column",gap:8}}>{[...history].reverse().map((w,i)=>{const isE=exp===w.id;return<div key={w.id}><div style={{...S.cds,cursor:"pointer"}} onClick={()=>setExp(isE?null:w.id)}><div style={{display:"flex",justifyContent:"space-between",alignItems:"flex-start"}}><div style={{flex:1}}><div style={{fontSize:14,fontWeight:600,color:"#fff",marginBottom:3}}>{w.routineName}</div><div style={{...S.mt,fontSize:11,marginBottom:6}}>{new Date(w.date).toLocaleDateString("en-US",{month:"short",day:"numeric"})} · {fmtDur(w.duration)} · {(w.totalVolume||0).toLocaleString()} lbs</div></div><div style={{display:"flex",gap:6,alignItems:"center"}}><span style={{fontSize:10,color:"rgba(255,255,255,0.25)",transform:isE?"rotate(180deg)":"none",transition:"transform 0.2s"}}>▼</span><button onClick={e=>{e.stopPropagation();setCDel(w.id);}} style={{background:"none",border:"none",color:"rgba(255,255,255,0.2)",cursor:"pointer",fontSize:14}}>×</button></div></div>{w.prs?.length>0&&<span style={{display:"inline-block",padding:"2px 8px",borderRadius:6,fontSize:9,fontWeight:700,background:"rgba(251,191,36,0.1)",color:"#fbbf24",marginBottom:6}}>🏆 {w.prs.length} PR{w.prs.length>1?"s":""}</span>}<div style={{display:"flex",flexWrap:"wrap"}}>{(w.muscles||[]).map(m=><MP key={m} m={m}/>)}</div></div>{isE&&<div style={{padding:"8px 0",display:"flex",flexDirection:"column",gap:4}}>{(w.exercises||[]).map((ex,j)=>{const data=getExerciseById(ex.exerciseId);if(!data)return null;return<div key={j} style={S.cds}><button onClick={()=>onOpenExDetail(ex.exerciseId)} style={{display:"flex",alignItems:"center",gap:10,background:"none",border:"none",cursor:"pointer",width:"100%",textAlign:"left",marginBottom:6}}><EI id={ex.exerciseId} size={28}/><span style={{fontSize:12,fontWeight:600,color:"#fff"}}>{data.name}</span></button>{(ex.sets||[]).map((s,k)=><div key={k} style={{display:"flex",gap:12,paddingLeft:38,marginBottom:2}}><span style={{fontSize:10,fontWeight:600,color:"rgba(255,255,255,0.3)",width:20}}>{k+1}</span><span style={{fontSize:11,fontWeight:600,color:s.isPR?"#fbbf24":"rgba(255,255,255,0.65)"}}>{s.weight} × {s.reps}{s.isPR?" ⭐":""}</span></div>)}</div>;})}</div>}</div>;})}</div>}{cDel&&<Confirm title="Delete workout?" msg="This will be permanently removed." ok="Delete" color="#f87171" onOk={()=>{onDeleteWorkout(cDel);setCDel(null);}} onNo={()=>setCDel(null)}/>}</div>;}

// ─── CALENDAR ───────────────────────────────────────────────────────────────
function CalendarScreen({history,routines,onOpenExDetail,onStartRoutine}){const{accent}=useTheme();const S=useS();const[mOff,setMOff]=useState(0),[selDay,setSelDay]=useState(null),[showTmpl,setShowTmpl]=useState(false),[showAssign,setShowAssign]=useState(null);const now=new Date(),vm=new Date(now.getFullYear(),now.getMonth()-mOff,1);const yr=vm.getFullYear(),mo=vm.getMonth();const fd=(new Date(yr,mo,1).getDay()+6)%7;const dim=new Date(yr,mo+1,0).getDate();const mn=vm.toLocaleDateString("en-US",{month:"long",year:"numeric"});const wMap=useMemo(()=>{const m={};(history||[]).forEach(w=>{const k=dKey(new Date(w.date));if(!m[k])m[k]=[];m[k].push(w);});return m;},[history]);const tmpl=LS.get("dialed_weekly_template",{});const plans=LS.get("dialed_plans",{});const tKey=dKey(now);
const getPlan=k=>{if(plans[k])return plans[k];const d=new Date(k+"T12:00:00");return tmpl[DS[(d.getDay()+6)%7]]||null;};
const assignOO=(k,rid)=>{const p=LS.get("dialed_plans",{});if(rid)p[k]={routineId:rid,time:null};else delete p[k];LS.set("dialed_plans",p);setShowAssign(null);};
const selW=selDay?wMap[selDay]||[]:[];const selP=selDay?getPlan(selDay):null;const selF=selDay?selDay>=tKey:false;

return<div style={S.pg}><div style={{paddingTop:56,marginBottom:20}}><div style={{display:"flex",justifyContent:"space-between",alignItems:"center"}}><h1 style={S.tt}>Calendar</h1><button onClick={()=>setShowTmpl(true)} style={{fontSize:12,fontWeight:600,color:accent,background:"none",border:"none",cursor:"pointer",fontFamily:"'Outfit',sans-serif"}}>Schedule</button></div></div>

<div style={{display:"flex",justifyContent:"space-between",alignItems:"center",marginBottom:16}}><button onClick={()=>setMOff(mOff+1)} style={{background:"none",border:"none",color:"rgba(255,255,255,0.4)",cursor:"pointer",fontSize:14,padding:8}}>◀</button><span style={{fontSize:15,fontWeight:700,color:"#fff"}}>{mn}</span><button onClick={()=>setMOff(Math.max(0,mOff-1))} style={{background:"none",border:"none",color:mOff>0?"rgba(255,255,255,0.4)":"rgba(255,255,255,0.12)",cursor:mOff>0?"pointer":"default",fontSize:14,padding:8}}>▶</button></div>

<div style={{display:"grid",gridTemplateColumns:"repeat(7,1fr)",gap:3,marginBottom:4}}>{DL.map((d,i)=><div key={i} style={{textAlign:"center",fontSize:10,fontWeight:700,color:"rgba(255,255,255,0.45)",padding:"4px 0"}}>{d}</div>)}</div>

<div style={{display:"grid",gridTemplateColumns:"repeat(7,1fr)",gap:3,marginBottom:20}}>
{Array.from({length:fd}).map((_,i)=><div key={`e${i}`} style={{minHeight:60}}/>)}
{Array.from({length:dim}).map((_,i)=>{const day=i+1,k=`${yr}-${pad(mo+1)}-${pad(day)}`;const hasW=!!wMap[k];const plan=!hasW?getPlan(k):null;const isT=k===tKey;const isSel=k===selDay;const rName=hasW?wMap[k][0].routineName:plan?routines.find(r=>r.id===plan.routineId)?.name:null;const time=plan?.time?fmt12(plan.time):null;
return<button key={day} onClick={()=>setSelDay(isSel?null:k)} style={{minHeight:60,borderRadius:10,border:isSel?`1.5px solid ${accent}`:isT?`1px solid rgba(255,255,255,0.2)`:"1px solid rgba(255,255,255,0.06)",background:isSel?hx(accent,.1):hasW?"rgba(255,255,255,0.05)":"rgba(255,255,255,0.02)",cursor:"pointer",display:"flex",flexDirection:"column",alignItems:"flex-start",padding:"4px 5px",gap:1,overflow:"hidden"}}>
<span style={{fontSize:11,fontWeight:isT?700:600,color:isT?"#fff":hasW?"rgba(255,255,255,0.85)":"rgba(255,255,255,0.6)",alignSelf:"flex-end"}}>{day}</span>
{rName&&<span style={{fontSize:7.5,fontWeight:600,color:hasW?accent:hx(accent,.65),lineHeight:1.2,overflow:"hidden",textOverflow:"ellipsis",whiteSpace:"nowrap",width:"100%"}}>{rName}</span>}
{time&&!hasW&&<span style={{fontSize:7,fontWeight:500,color:"rgba(255,255,255,0.4)"}}>{time}</span>}
{hasW&&<div style={{width:4,height:4,borderRadius:2,background:accent,marginTop:"auto"}}/>}
</button>;})}
</div>

{selDay&&<div>{selW.length>0?selW.map(w=><div key={w.id} style={{...S.cd,marginBottom:8}}><div style={{fontSize:14,fontWeight:600,color:"#fff",marginBottom:3}}>{w.routineName}</div><div style={{...S.mt,fontSize:11,marginBottom:8}}>{fmtDur(w.duration)} · {(w.totalVolume||0).toLocaleString()} lbs</div>{(w.exercises||[]).map((ex,j)=>{const data=getExerciseById(ex.exerciseId);if(!data)return null;return<div key={j} style={{display:"flex",alignItems:"center",gap:8,padding:"4px 0",borderTop:"1px solid rgba(255,255,255,0.05)"}}><button onClick={()=>onOpenExDetail(ex.exerciseId)} style={{display:"flex",alignItems:"center",gap:8,background:"none",border:"none",cursor:"pointer",flex:1,textAlign:"left"}}><EI id={ex.exerciseId} size={24}/><span style={{fontSize:11,fontWeight:600,color:"rgba(255,255,255,0.75)"}}>{data.name}</span></button></div>;})}</div>)
:selP&&selF?<div style={S.cda(accent)}><div style={{fontSize:12,fontWeight:600,color:accent,marginBottom:4}}>Planned</div><div style={{fontSize:14,fontWeight:600,color:"#fff",marginBottom:3}}>{routines.find(r=>r.id===selP.routineId)?.name||"Routine"}</div>{selP.time&&<div style={{fontSize:11,color:"rgba(255,255,255,0.45)"}}>{fmt12(selP.time)}</div>}<div style={{display:"flex",gap:8,marginTop:10}}><button onClick={()=>setShowAssign(selDay)} style={{...S.bg,flex:1,fontSize:11,padding:"8px 0"}}>Change</button><button onClick={()=>{const r=routines.find(x=>x.id===selP.routineId);if(r)onStartRoutine(r);}} style={{...S.bp,flex:1,fontSize:11,padding:"8px 0"}}>Start Now</button></div></div>
:selF?<button onClick={()=>setShowAssign(selDay)} style={{...S.bg,width:"100%"}}>+ Plan Workout</button>
:<p style={{...S.mt,textAlign:"center"}}>No workout this day</p>}</div>}

{showAssign&&<div style={{position:"fixed",inset:0,zIndex:100,display:"flex",alignItems:"center",justifyContent:"center",fontFamily:"'Outfit',sans-serif"}}><div onClick={()=>setShowAssign(null)} style={{position:"absolute",inset:0,background:"rgba(0,0,0,0.5)"}}/><div style={{position:"relative",width:"85%",maxWidth:360,...glass,padding:24}}><p style={{fontSize:17,fontWeight:700,color:"#fff",marginBottom:4}}>Plan Workout</p><p style={{...S.mt,marginBottom:16}}>{new Date(showAssign+"T12:00:00").toLocaleDateString("en-US",{weekday:"long",month:"short",day:"numeric"})}</p><div style={{display:"flex",flexDirection:"column",gap:6}}>{routines.map(r=><button key={r.id} onClick={()=>assignOO(showAssign,r.id)} style={{...S.cds,textAlign:"left",cursor:"pointer",fontSize:14,fontWeight:600,color:"#fff"}}>{r.name}</button>)}<button onClick={()=>assignOO(showAssign,null)} style={{...S.bg,color:"#f87171",borderColor:"rgba(248,113,113,0.15)",marginTop:4}}>Remove Plan</button></div></div></div>}
{showTmpl&&<TemplateEditor routines={routines} onClose={()=>setShowTmpl(false)}/>}
</div>;}

// ─── AWARDS ─────────────────────────────────────────────────────────────────
function AwardsScreen({history}){const{accent}=useTheme();const S=useS();const uIds=checkAch(history);const unlocked=ACHIEVEMENTS.filter(a=>uIds.includes(a.id));const locked=ACHIEVEMENTS.filter(a=>!uIds.includes(a.id));const ratio=ACHIEVEMENTS.length>0?(unlocked.length/ACHIEVEMENTS.length)*100:0;return<div style={S.pg}><div style={{paddingTop:56,marginBottom:6}}><h1 style={S.tt}>Achievements</h1><p style={{...S.mt,marginTop:4}}>{unlocked.length} of {ACHIEVEMENTS.length} unlocked</p></div><div style={{height:4,background:"rgba(255,255,255,0.06)",borderRadius:2,marginBottom:24,overflow:"hidden"}}><div style={{height:"100%",width:`${ratio}%`,background:accent,borderRadius:2}}/></div>{unlocked.length>0&&<><div style={{...S.lb,color:accent,marginBottom:10}}>UNLOCKED</div><div style={{display:"flex",flexDirection:"column",gap:8,marginBottom:24}}>{unlocked.map(a=><div key={a.id} style={S.cda(accent)}><div style={{display:"flex",alignItems:"center",gap:14}}><span style={{fontSize:22}}>{a.icon}</span><div style={{flex:1}}><div style={{fontSize:13,fontWeight:600,color:"#fff"}}>{a.title}</div><div style={{fontSize:11,fontWeight:500,color:"rgba(255,255,255,0.4)"}}>{a.desc}</div></div><span style={{fontSize:10,fontWeight:600,color:accent,background:hx(accent,.1),padding:"3px 8px",borderRadius:100}}>Top {a.percentile}%</span></div></div>)}</div></>}{locked.length>0&&<><div style={{...S.lb,marginBottom:10}}>LOCKED</div><div style={{display:"grid",gridTemplateColumns:"1fr 1fr",gap:8}}>{locked.map(a=><div key={a.id} style={{...S.cd,background:"rgba(255,255,255,0.02)",border:"0.5px solid rgba(255,255,255,0.06)"}}><span style={{fontSize:18,opacity:.15}}>{a.icon}</span><div style={{fontSize:11,fontWeight:600,color:"rgba(255,255,255,0.2)",marginTop:6}}>{a.title}</div><div style={{fontSize:10,fontWeight:500,color:"rgba(255,255,255,0.12)",marginTop:2}}>{a.desc}</div></div>)}</div></>}</div>;}

// ─── MAIN APP ───────────────────────────────────────────────────────────────
export default function App(){
const[profile,setProfile]=useState(()=>LS.get("dialed_profile",null));
const[routines,setRoutines]=useState(()=>LS.get("dialed_routines",[]));
const[history,setHistory]=useState(()=>LS.get("dialed_history",[]));
const[tab,setTab]=useState("home");const[view,setView]=useState("tabs");
const[editR,setEditR]=useState(null);const[activeR,setActiveR]=useState(null);const[lastW,setLastW]=useState(null);
const[showSettings,setShowSettings]=useState(false);const[exDetail,setExDetail]=useState(null);
const theme=THEMES[profile?.theme||"emerald"]||THEMES.emerald;
useEffect(()=>{LS.set("dialed_routines",routines);},[routines]);
useEffect(()=>{LS.set("dialed_history",history);},[history]);
const up=p=>{setProfile(p);LS.set("dialed_profile",p);};
const saveR=r=>{const i=routines.findIndex(x=>x.id===r.id);if(i>=0){const u=[...routines];u[i]=r;setRoutines(u);}else setRoutines([...routines,r]);setView("tabs");setEditR(null);};
const startR=r=>{setActiveR(r);setView("workout");};

return<ThemeCtx.Provider value={theme}><GlowBG/>
{!profile?.onboarded?<Onboarding onComplete={()=>{setProfile(LS.get("dialed_profile"));setRoutines(LS.get("dialed_routines",[]));}}/>:
view==="builder"?<RoutineBuilder routine={editR} onSave={saveR} onBack={()=>{setView("tabs");setEditR(null);}} onDelete={id=>setRoutines(routines.filter(r=>r.id!==id))} history={history}/>:
view==="workout"?<LiveWorkout routine={activeR} history={history} onFinish={w=>{setHistory([...history,w]);setLastW(w);setView("summary");setActiveR(null);}} onCancel={()=>{setView("tabs");setActiveR(null);}}/>:
view==="summary"&&lastW?<WorkoutSummary workout={lastW} onDone={()=>{setView("tabs");setLastW(null);}}/>:
<>{tab==="home"&&<HomeScreen profile={profile} history={history} routines={routines} onStartRoutine={startR} onNewRoutine={()=>{setEditR(null);setView("builder");}} onEditRoutine={r=>{setEditR(r);setView("builder");}} onQuickStart={()=>{setActiveR({name:"Quick Workout",exercises:[]});setView("workout");}} onOpenSettings={()=>setShowSettings(true)}/>}
{tab==="history"&&<HistoryScreen history={history} onDeleteWorkout={id=>setHistory(history.filter(w=>w.id!==id))} onOpenExDetail={id=>setExDetail(id)}/>}
{tab==="calendar"&&<CalendarScreen history={history} routines={routines} onOpenExDetail={id=>setExDetail(id)} onStartRoutine={startR}/>}
{tab==="awards"&&<AwardsScreen history={history}/>}
<Nav tab={tab} setTab={setTab}/>
</>}
{showSettings&&<Settings profile={profile} onClose={()=>setShowSettings(false)} onUpdate={up}/>}
{exDetail&&<ExDetail exerciseId={exDetail} history={history} onClose={()=>setExDetail(null)}/>}
<style>{globalCSS}</style>
</ThemeCtx.Provider>;}

const globalCSS=`
@import url('https://fonts.googleapis.com/css2?family=Outfit:wght@300;400;500;600;700;800&display=swap');
*,*::before,*::after{box-sizing:border-box;margin:0;padding:0}
html,body,#root{background:#0a110e;color:#fff;font-family:'Outfit',sans-serif;-webkit-font-smoothing:antialiased;min-height:100vh;overflow-x:hidden}
input[type="number"]::-webkit-inner-spin-button,input[type="number"]::-webkit-outer-spin-button{-webkit-appearance:none;margin:0}
input[type="number"]{-moz-appearance:textfield}
input::placeholder,textarea::placeholder{color:rgba(255,255,255,0.25)}
select{-webkit-appearance:none}
button{-webkit-tap-highlight-color:transparent}
::-webkit-scrollbar{width:0;height:0}
@keyframes fadeIn{from{opacity:0}to{opacity:1}}
`;
